USE aplikasi;

REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('9901', 'PPI', 1, 'PPI', 1, 'ppi.Link', 'x-fa fa-newspaper-o', 1, 1, 'ppi');
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('990101', 'GROUP & KEGIATAN', 2, 'Group & Kegiatan', 1, 'ppi.kegiatan.group.Workspace', 'x-fa fa-edit', 0, 0, NULL);
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('990102', 'KEGIATAN EVALUASI', 2, 'Kegiatan Evaluasi', 1, NULL, 'x-fa fa-tv', 1, 0, NULL);
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('99010201', 'INDIVIDU', 3, 'Individu', 1, 'ppi.audit.individu.List', 'x-fa fa-user', 0, 0, NULL);
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('99010202', 'RUANGAN', 3, 'Ruangan', 1, 'ppi.penilaian.List', 'x-fa fa-bed', 0, 0, NULL);
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('99010203', 'SARAN DAN TINDAK LANJUT', 3, 'Saran & Tindak Lanjut', 1, 'ppi.penilaian.tindaklanjut.Workspace', 'x-fa fa-stack-exchange', 0, 0, NULL);
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('990103', 'KEGIATAN HARIAN', 2, 'Kegiatan Harian', 1, 'ppi.penilaian.harian.Workspace', 'x-fa fa-calendar', 0, 0, NULL);
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('990104', 'HAIs', 2, 'HAIs', 1, 'ppi.hais.Workspace', 'x-fa fa-newspaper-o', 0, 0, NULL);
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('990105', 'PELAPORAN', 2, 'Pelaporan', 1, NULL, 'x-fa fa-stethoscope', 1, 0, NULL);
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('99010501', 'TERTUSUK JARUM', 3, 'Tertusuk Jarum', 1, 'ppi.pelaporan.tertusukjarum.Workspace', 'x-fa fa-thumb-tack', 0, 0, NULL);
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('99010502', 'LIMBAH INFEKSIUS', 3, 'Limbah Infeksius', 1, 'ppi.pelaporan.limbainfeksius.Workspace', 'x-fa fa-recycle', 0, 0, NULL);
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('990106', 'AUDIT', 2, 'Audit', 1, NULL, 'x-fa fa-book', 1, 0, NULL);
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('99010601', 'INDIVIDU', 3, 'Individu', 1, 'ppi.audit.individu.Workspace', 'x-fa fa-user', 0, 0, NULL);
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('99010602', 'RUANGAN', 3, 'Ruangan', 1, 'ppi.audit.ruangan.Workspace', 'x-fa fa-bed', 0, 0, NULL);
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('990107', 'LAPORAN', 2, 'Laporan', 1, 'ppi.laporan.Workspace', 'x-fa fa-print', 0, 0, NULL);
