USE aplikasi;
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='28';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='2801';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='2802';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='280201';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='280202';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='280203';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='2803';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='2804';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='2805';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='280501';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='280502';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='2806';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='280601';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='280602';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='2807';