USE `master`;

ALTER TABLE `mrconso`
	ADD COLUMN `VALIDCODE` CHAR(1) NOT NULL DEFAULT '' COMMENT '1=Bisa di pilih' AFTER `VERSION`,
	ADD COLUMN `ACCPDX` CHAR(1) NOT NULL DEFAULT '' COMMENT 'Y=Bisa jadi diagnosa utama (utk diagnosa)',
	ADD COLUMN `CODE_ASTERISK` CHAR(15) NOT NULL DEFAULT '' COMMENT ' (utk diagnosa)',
	ADD COLUMN `ASTERISK` CHAR(1) NOT NULL DEFAULT '' COMMENT ' (utk diagnosa)',
	ADD COLUMN `IM` CHAR(1) NOT NULL DEFAULT '' COMMENT 'Indonesian Modification',
	ADD COLUMN `ICD_TYPE` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1=Diagnosa; 2=Prosedur';