USE medicalrecord;

ALTER TABLE `diagnosa`
	ADD COLUMN `INA_GROUPER` TINYINT(4) NOT NULL DEFAULT '0' AFTER `STATUS`,
	ADD INDEX `INA_GROUPER` (`INA_GROUPER`);

ALTER TABLE `prosedur`
	ADD COLUMN `INA_GROUPER` TINYINT(4) NOT NULL DEFAULT '0' AFTER `STATUS`,
	ADD INDEX `INA_GROUPER` (`INA_GROUPER`);