USE aplikasi;
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='32';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='3201';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='320101';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='320102';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='3202';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='3203';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='320301';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='320302';
DELETE FROM `aplikasi`.`modules` WHERE  `ID`='320303';