USE `master`;

ALTER TABLE `kelas_simrs_kemkes`
	ADD COLUMN `ID` SMALLINT NOT NULL AUTO_INCREMENT FIRST,
	DROP PRIMARY KEY,
	ADD UNIQUE INDEX `KELAS_KEMKES_KELAS` (`KELAS`, `KEMKES_KELAS`),
	ADD PRIMARY KEY (`ID`);