USE master;

ALTER TABLE `ruangan_simrs_kemkes`
	ADD COLUMN `ID` SMALLINT NOT NULL AUTO_INCREMENT FIRST,
	DROP PRIMARY KEY,
	ADD UNIQUE INDEX `RUANGAN_KEMKES_RUANGAN` (`RUANGAN`, `KEMKES_RUANGAN`),
	ADD PRIMARY KEY (`ID`);