<?php
return [
    'router' => [
        'routes' => [
            'pendaftaran.rest.pendaftaran' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/pendaftaran[/:nomor]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\Pendaftaran\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.penanggung-jawab-pasien' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/penanggungjawabpasien[/:id]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\PenanggungJawabPasien\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.kontak-penanggung-jawab' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/kontak-penanggungjawab[/:id]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\KontakPenanggungJawab\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.kip-penanggung-jawab' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/kartu-identitas-penanggungjawab[/:id]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\KIPPenanggungJawab\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.tujuan-pasien' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/tujuanpasien[/:nopen]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\TujuanPasien\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.surat-rujukan-pasien' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/suratrujukanpasien[/:norm]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\SuratRujukanPasien\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.penjamin' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/penjamin[/:nopen]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\Penjamin\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.history' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/history[/:norm]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\History\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.kunjungan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/kunjungan[/:nopen]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\Kunjungan\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.konsul' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/konsul[/:nomor]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\Konsul\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.jawaban-konsul' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/jawabankonsul[/:nomor]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\JawabanKonsul\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.reservasi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/reservasi[/:nomor]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\Reservasi\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.mutasi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/mutasi[/:nomor]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\Mutasi\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.antrian-ruangan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/antrianruangan[/:id]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\AntrianRuangan\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.pembatalan-kunjungan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/pembatalankunjungan[/:id]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\PembatalanKunjungan\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.panggilan-antrian-ruangan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/panggilanantrianruangan[/:id]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\PanggilanAntrianRuangan\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.perubahan-tanggal-kunjungan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/perubahantanggalkunjungan[/:id]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\PerubahanTanggalKunjungan\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.kecelakaan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/kecelakaan[/:kecelakaan_id]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\Kecelakaan\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.rujukan-keluar' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/rujukan/keluar[/:rujukan_keluar_id]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\RujukanKeluar\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.pemohon' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/pemohon[/:id]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\Pemohon\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.antrian-tempat-tidur' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/antrian/tempat-tidur[/:id]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\AntrianTempatTidur\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.pengantar-pasien' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/pengantarpasien[/:id]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\PengantarPasien\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.kartu-identitas-pengantar-pasien' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/kartu-identitas-pengantar-pasien[/:kartu_identitas_pengantar_pasien_id]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\KartuIdentitasPengantarPasien\\Controller',
                    ],
                ],
            ],
            'pendaftaran.rest.kontak-pengantar-pasien' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pendaftaran/kontak-pengantar-pasien[/:kontak_pengantar_pasien_id]',
                    'defaults' => [
                        'controller' => 'Pendaftaran\\V1\\Rest\\KontakPengantarPasien\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'api-tools-versioning' => [
        'uri' => [
            0 => 'pendaftaran.rest.pendaftaran',
            1 => 'pendaftaran.rest.penanggung-jawab-pasien',
            2 => 'pendaftaran.rest.kontak-penanggung-jawab',
            3 => 'pendaftaran.rest.kip-penanggung-jawab',
            4 => 'pendaftaran.rest.tujuan-pasien',
            5 => 'pendaftaran.rest.surat-rujukan-pasien',
            6 => 'pendaftaran.rest.penjamin',
            7 => 'pendaftaran.rest.history',
            8 => 'pendaftaran.rest.kunjungan',
            9 => 'pendaftaran.rest.konsul',
            10 => 'pendaftaran.rest.jawaban-konsul',
            11 => 'pendaftaran.rest.reservasi',
            12 => 'pendaftaran.rest.mutasi',
            13 => 'pendaftaran.rest.antrian-ruangan',
            14 => 'pendaftaran.rest.pembatalan-kunjungan',
            15 => 'pendaftaran.rest.panggilan-antrian-ruangan',
            16 => 'pendaftaran.rest.perubahan-tanggal-kunjungan',
            17 => 'pendaftaran.rest.kecelakaan',
            18 => 'pendaftaran.rest.rujukan-keluar',
            19 => 'pendaftaran.rest.pemohon',
            20 => 'pendaftaran.rest.antrian-tempat-tidur',
            21 => 'pendaftaran.rest.pengantar-pasien',
            22 => 'pendaftaran.rest.kartu-identitas-pengantar-pasien',
            23 => 'pendaftaran.rest.kontak-pengantar-pasien',
        ],
    ],
    'service_manager' => [
        'factories' => [
            \Pendaftaran\V1\Rest\Pendaftaran\PendaftaranResource::class => \Pendaftaran\V1\Rest\Pendaftaran\PendaftaranResourceFactory::class,
            \Pendaftaran\V1\Rest\PenanggungJawabPasien\PenanggungJawabPasienResource::class => \Pendaftaran\V1\Rest\PenanggungJawabPasien\PenanggungJawabPasienResourceFactory::class,
            \Pendaftaran\V1\Rest\KontakPenanggungJawab\KontakPenanggungJawabResource::class => \Pendaftaran\V1\Rest\KontakPenanggungJawab\KontakPenanggungJawabResourceFactory::class,
            \Pendaftaran\V1\Rest\KIPPenanggungJawab\KIPPenanggungJawabResource::class => \Pendaftaran\V1\Rest\KIPPenanggungJawab\KIPPenanggungJawabResourceFactory::class,
            \Pendaftaran\V1\Rest\TujuanPasien\TujuanPasienResource::class => \Pendaftaran\V1\Rest\TujuanPasien\TujuanPasienResourceFactory::class,
            \Pendaftaran\V1\Rest\SuratRujukanPasien\SuratRujukanPasienResource::class => \Pendaftaran\V1\Rest\SuratRujukanPasien\SuratRujukanPasienResourceFactory::class,
            \Pendaftaran\V1\Rest\Penjamin\PenjaminResource::class => \Pendaftaran\V1\Rest\Penjamin\PenjaminResourceFactory::class,
            \Pendaftaran\V1\Rest\History\HistoryResource::class => \Pendaftaran\V1\Rest\History\HistoryResourceFactory::class,
            \Pendaftaran\V1\Rest\Kunjungan\KunjunganResource::class => \Pendaftaran\V1\Rest\Kunjungan\KunjunganResourceFactory::class,
            \Pendaftaran\V1\Rest\Konsul\KonsulResource::class => \Pendaftaran\V1\Rest\Konsul\KonsulResourceFactory::class,
            \Pendaftaran\V1\Rest\JawabanKonsul\JawabanKonsulResource::class => \Pendaftaran\V1\Rest\JawabanKonsul\JawabanKonsulResourceFactory::class,
            \Pendaftaran\V1\Rest\Reservasi\ReservasiResource::class => \Pendaftaran\V1\Rest\Reservasi\ReservasiResourceFactory::class,
            \Pendaftaran\V1\Rest\Mutasi\MutasiResource::class => \Pendaftaran\V1\Rest\Mutasi\MutasiResourceFactory::class,
            \Pendaftaran\V1\Rest\AntrianRuangan\AntrianRuanganResource::class => \Pendaftaran\V1\Rest\AntrianRuangan\AntrianRuanganResourceFactory::class,
            \Pendaftaran\V1\Rest\PembatalanKunjungan\PembatalanKunjunganResource::class => \Pendaftaran\V1\Rest\PembatalanKunjungan\PembatalanKunjunganResourceFactory::class,
            \Pendaftaran\V1\Rest\PanggilanAntrianRuangan\PanggilanAntrianRuanganResource::class => \Pendaftaran\V1\Rest\PanggilanAntrianRuangan\PanggilanAntrianRuanganResourceFactory::class,
            \Pendaftaran\V1\Rest\PerubahanTanggalKunjungan\PerubahanTanggalKunjunganResource::class => \Pendaftaran\V1\Rest\PerubahanTanggalKunjungan\PerubahanTanggalKunjunganResourceFactory::class,
            \Pendaftaran\V1\Rest\Kecelakaan\KecelakaanResource::class => \Pendaftaran\V1\Rest\Kecelakaan\KecelakaanResourceFactory::class,
            \Pendaftaran\V1\Rest\RujukanKeluar\RujukanKeluarResource::class => \Pendaftaran\V1\Rest\RujukanKeluar\RujukanKeluarResourceFactory::class,
            \Pendaftaran\V1\Rest\Pemohon\PemohonResource::class => \Pendaftaran\V1\Rest\Pemohon\PemohonResourceFactory::class,
            \Pendaftaran\V1\Rest\AntrianTempatTidur\AntrianTempatTidurResource::class => \Pendaftaran\V1\Rest\AntrianTempatTidur\AntrianTempatTidurResourceFactory::class,
            \Pendaftaran\V1\Rest\PengantarPasien\PengantarPasienResource::class => \Pendaftaran\V1\Rest\PengantarPasien\PengantarPasienResourceFactory::class,
            \Pendaftaran\V1\Rest\KartuIdentitasPengantarPasien\KartuIdentitasPengantarPasienResource::class => \Pendaftaran\V1\Rest\KartuIdentitasPengantarPasien\KartuIdentitasPengantarPasienResourceFactory::class,
            \Pendaftaran\V1\Rest\KontakPengantarPasien\KontakPengantarPasienResource::class => \Pendaftaran\V1\Rest\KontakPengantarPasien\KontakPengantarPasienResourceFactory::class,
        ],
    ],
    'api-tools-rest' => [
        'Pendaftaran\\V1\\Rest\\Pendaftaran\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\Pendaftaran\PendaftaranResource::class,
            'route_name' => 'pendaftaran.rest.pendaftaran',
            'route_identifier_name' => 'nomor',
            'collection_name' => 'pendaftaran',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOMOR',
                1 => 'NORM',
                2 => 'start',
                3 => 'limit',
                4 => 'REFERENSI',
                5 => 'COLUMNS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\Pendaftaran\PendaftaranEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\Pendaftaran\PendaftaranCollection::class,
            'service_name' => 'pendaftaran',
        ],
        'Pendaftaran\\V1\\Rest\\PenanggungJawabPasien\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\PenanggungJawabPasien\PenanggungJawabPasienResource::class,
            'route_name' => 'pendaftaran.rest.penanggung-jawab-pasien',
            'route_identifier_name' => 'id',
            'collection_name' => 'penanggung_jawab_pasien',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'REF',
                2 => 'SHDK',
                3 => 'JENIS_KELAMIN',
                4 => 'NAMA',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\PenanggungJawabPasien\PenanggungJawabPasienEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\PenanggungJawabPasien\PenanggungJawabPasienCollection::class,
            'service_name' => 'PenanggungJawabPasien',
        ],
        'Pendaftaran\\V1\\Rest\\KontakPenanggungJawab\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\KontakPenanggungJawab\KontakPenanggungJawabResource::class,
            'route_name' => 'pendaftaran.rest.kontak-penanggung-jawab',
            'route_identifier_name' => 'id',
            'collection_name' => 'kontak_penanggung_jawab',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ID',
                1 => 'JENIS',
                2 => 'NOMOR',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\KontakPenanggungJawab\KontakPenanggungJawabEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\KontakPenanggungJawab\KontakPenanggungJawabCollection::class,
            'service_name' => 'KontakPenanggungJawab',
        ],
        'Pendaftaran\\V1\\Rest\\KIPPenanggungJawab\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\KIPPenanggungJawab\KIPPenanggungJawabResource::class,
            'route_name' => 'pendaftaran.rest.kip-penanggung-jawab',
            'route_identifier_name' => 'id',
            'collection_name' => 'kip_penanggung_jawab',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ID',
                1 => 'JENIS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\KIPPenanggungJawab\KIPPenanggungJawabEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\KIPPenanggungJawab\KIPPenanggungJawabCollection::class,
            'service_name' => 'KIPPenanggungJawab',
        ],
        'Pendaftaran\\V1\\Rest\\TujuanPasien\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\TujuanPasien\TujuanPasienResource::class,
            'route_name' => 'pendaftaran.rest.tujuan-pasien',
            'route_identifier_name' => 'nopen',
            'collection_name' => 'tujuan_pasien',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'RUANGAN',
                2 => 'STATUS',
                3 => 'TANGGAL',
                4 => 'COLUMNS',
                5 => 'REFERENSI',
                6 => 'NORM',
                7 => 'limit',
                8 => 'start',
                9 => 'sort',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\TujuanPasien\TujuanPasienEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\TujuanPasien\TujuanPasienCollection::class,
            'service_name' => 'TujuanPasien',
        ],
        'Pendaftaran\\V1\\Rest\\SuratRujukanPasien\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\SuratRujukanPasien\SuratRujukanPasienResource::class,
            'route_name' => 'pendaftaran.rest.surat-rujukan-pasien',
            'route_identifier_name' => 'norm',
            'collection_name' => 'surat_rujukan_pasien',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'PPK',
                1 => 'NORM',
                2 => 'NOMOR',
                3 => 'TANGGAL',
                4 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\SuratRujukanPasien\SuratRujukanPasienEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\SuratRujukanPasien\SuratRujukanPasienCollection::class,
            'service_name' => 'SuratRujukanPasien',
        ],
        'Pendaftaran\\V1\\Rest\\Penjamin\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\Penjamin\PenjaminResource::class,
            'route_name' => 'pendaftaran.rest.penjamin',
            'route_identifier_name' => 'nopen',
            'collection_name' => 'penjamin',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'JENIS',
                1 => 'NOPEN',
                2 => 'NOMOR',
                3 => 'NORM',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\Penjamin\PenjaminEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\Penjamin\PenjaminCollection::class,
            'service_name' => 'Penjamin',
        ],
        'Pendaftaran\\V1\\Rest\\History\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\History\HistoryResource::class,
            'route_name' => 'pendaftaran.rest.history',
            'route_identifier_name' => 'norm',
            'collection_name' => 'history',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TYPE',
                1 => 'NORM',
                2 => 'NOMOR',
                3 => 'NOPEN',
                4 => 'RUANGAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\History\HistoryEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\History\HistoryCollection::class,
            'service_name' => 'history',
        ],
        'Pendaftaran\\V1\\Rest\\Kunjungan\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\Kunjungan\KunjunganResource::class,
            'route_name' => 'pendaftaran.rest.kunjungan',
            'route_identifier_name' => 'nopen',
            'collection_name' => 'kunjungan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'RUANGAN',
                2 => 'MASUK',
                3 => 'NORM',
                4 => 'start',
                5 => 'limit',
                6 => 'QUERY',
                7 => 'JENIS_KUNJUNGAN',
                8 => 'REF',
                9 => 'STATUS',
                10 => 'NOMOR',
                11 => 'HISTORY',
                12 => 'REFERENSI',
                13 => 'COLUMNS',
                14 => 'TAGIHAN',
                15 => 'JENIS_KELAMIN',
                16 => 'NAMA',
                17 => 'MY_PASIEN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\Kunjungan\KunjunganEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\Kunjungan\KunjunganCollection::class,
            'service_name' => 'kunjungan',
        ],
        'Pendaftaran\\V1\\Rest\\Konsul\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\Konsul\KonsulResource::class,
            'route_name' => 'pendaftaran.rest.konsul',
            'route_identifier_name' => 'nomor',
            'collection_name' => 'konsul',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'ASAL',
                2 => 'TUJUAN',
                3 => 'STATUS',
                4 => 'limit',
                5 => 'start',
                6 => 'KUNJUNGAN',
                7 => 'NOMOR',
                8 => 'JENIS_KUNJUNGAN',
                9 => 'NORM',
                10 => 'HISTORY',
                11 => 'TANGGAL',
                12 => 'COLUMNS',
                13 => 'REFERENSI',
                14 => 'sort',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\Konsul\KonsulEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\Konsul\KonsulCollection::class,
            'service_name' => 'Konsul',
        ],
        'Pendaftaran\\V1\\Rest\\JawabanKonsul\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\JawabanKonsul\JawabanKonsulResource::class,
            'route_name' => 'pendaftaran.rest.jawaban-konsul',
            'route_identifier_name' => 'nomor',
            'collection_name' => 'jawaban_konsul',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOMOR',
                1 => 'KONSUL_NOMOR',
                2 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\JawabanKonsul\JawabanKonsulEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\JawabanKonsul\JawabanKonsulCollection::class,
            'service_name' => 'JawabanKonsul',
        ],
        'Pendaftaran\\V1\\Rest\\Reservasi\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\Reservasi\ReservasiResource::class,
            'route_name' => 'pendaftaran.rest.reservasi',
            'route_identifier_name' => 'nomor',
            'collection_name' => 'reservasi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOMOR',
                1 => 'TANGGAL',
                2 => 'RUANG_KAMAR_TIDUR',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\Reservasi\ReservasiEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\Reservasi\ReservasiCollection::class,
            'service_name' => 'Reservasi',
        ],
        'Pendaftaran\\V1\\Rest\\Mutasi\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\Mutasi\MutasiResource::class,
            'route_name' => 'pendaftaran.rest.mutasi',
            'route_identifier_name' => 'nomor',
            'collection_name' => 'mutasi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'ASAL',
                2 => 'TUJUAN',
                3 => 'STATUS',
                4 => 'limit',
                5 => 'start',
                6 => 'KUNJUNGAN',
                7 => 'HISTORY',
                8 => 'TANGGAL',
                9 => 'COLUMNS',
                10 => 'REFERENSI',
                11 => 'NORM',
                12 => 'sort',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\Mutasi\MutasiEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\Mutasi\MutasiCollection::class,
            'service_name' => 'mutasi',
        ],
        'Pendaftaran\\V1\\Rest\\AntrianRuangan\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\AntrianRuangan\AntrianRuanganResource::class,
            'route_name' => 'pendaftaran.rest.antrian-ruangan',
            'route_identifier_name' => 'id',
            'collection_name' => 'antrian_ruangan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'RUANGAN',
                1 => 'TANGGAL',
                2 => 'NOMOR',
                3 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\AntrianRuangan\AntrianRuanganEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\AntrianRuangan\AntrianRuanganCollection::class,
            'service_name' => 'AntrianRuangan',
        ],
        'Pendaftaran\\V1\\Rest\\PembatalanKunjungan\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\PembatalanKunjungan\PembatalanKunjunganResource::class,
            'route_name' => 'pendaftaran.rest.pembatalan-kunjungan',
            'route_identifier_name' => 'id',
            'collection_name' => 'pembatalan_kunjungan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'JENIS',
                2 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\PembatalanKunjungan\PembatalanKunjunganEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\PembatalanKunjungan\PembatalanKunjunganCollection::class,
            'service_name' => 'PembatalanKunjungan',
        ],
        'Pendaftaran\\V1\\Rest\\PanggilanAntrianRuangan\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\PanggilanAntrianRuangan\PanggilanAntrianRuanganResource::class,
            'route_name' => 'pendaftaran.rest.panggilan-antrian-ruangan',
            'route_identifier_name' => 'id',
            'collection_name' => 'panggilan_antrian_ruangan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'IN',
                1 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\PanggilanAntrianRuangan\PanggilanAntrianRuanganEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\PanggilanAntrianRuangan\PanggilanAntrianRuanganCollection::class,
            'service_name' => 'PanggilanAntrianRuangan',
        ],
        'Pendaftaran\\V1\\Rest\\PerubahanTanggalKunjungan\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\PerubahanTanggalKunjungan\PerubahanTanggalKunjunganResource::class,
            'route_name' => 'pendaftaran.rest.perubahan-tanggal-kunjungan',
            'route_identifier_name' => 'id',
            'collection_name' => 'perubahan_tanggal_kunjungan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\PerubahanTanggalKunjungan\PerubahanTanggalKunjunganEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\PerubahanTanggalKunjungan\PerubahanTanggalKunjunganCollection::class,
            'service_name' => 'PerubahanTanggalKunjungan',
        ],
        'Pendaftaran\\V1\\Rest\\Kecelakaan\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\Kecelakaan\KecelakaanResource::class,
            'route_name' => 'pendaftaran.rest.kecelakaan',
            'route_identifier_name' => 'kecelakaan_id',
            'collection_name' => 'kecelakaan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\Kecelakaan\KecelakaanEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\Kecelakaan\KecelakaanCollection::class,
            'service_name' => 'Kecelakaan',
        ],
        'Pendaftaran\\V1\\Rest\\RujukanKeluar\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\RujukanKeluar\RujukanKeluarResource::class,
            'route_name' => 'pendaftaran.rest.rujukan-keluar',
            'route_identifier_name' => 'rujukan_keluar_id',
            'collection_name' => 'rujukan_keluar',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOMOR',
                1 => 'STATUS',
                2 => 'NOPEN',
                3 => 'KUNJUNGAN',
                4 => 'TUJUAN',
                5 => 'TUJUAN_RUANGAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\RujukanKeluar\RujukanKeluarEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\RujukanKeluar\RujukanKeluarCollection::class,
            'service_name' => 'RujukanKeluar',
        ],
        'Pendaftaran\\V1\\Rest\\Pemohon\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\Pemohon\PemohonResource::class,
            'route_name' => 'pendaftaran.rest.pemohon',
            'route_identifier_name' => 'id',
            'collection_name' => 'pemohon',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ID',
                1 => 'NIK',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\Pemohon\PemohonEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\Pemohon\PemohonCollection::class,
            'service_name' => 'Pemohon',
        ],
        'Pendaftaran\\V1\\Rest\\AntrianTempatTidur\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\AntrianTempatTidur\AntrianTempatTidurResource::class,
            'route_name' => 'pendaftaran.rest.antrian-tempat-tidur',
            'route_identifier_name' => 'id',
            'collection_name' => 'antrian_tempat_tidur',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NORM',
                1 => 'RENCANA_RUANGAN',
                2 => 'RENCANA_KELAS',
                3 => 'STATUS',
                4 => 'start',
                5 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\AntrianTempatTidur\AntrianTempatTidurEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\AntrianTempatTidur\AntrianTempatTidurCollection::class,
            'service_name' => 'AntrianTempatTidur',
        ],
        'Pendaftaran\\V1\\Rest\\PengantarPasien\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\PengantarPasien\PengantarPasienResource::class,
            'route_name' => 'pendaftaran.rest.pengantar-pasien',
            'route_identifier_name' => 'id',
            'collection_name' => 'pengantar_pasien',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'REF',
                2 => 'SHDK',
                3 => 'JENIS_KELAMIN',
                4 => 'NAMA',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\PengantarPasien\PengantarPasienEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\PengantarPasien\PengantarPasienCollection::class,
            'service_name' => 'PengantarPasien',
        ],
        'Pendaftaran\\V1\\Rest\\KartuIdentitasPengantarPasien\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\KartuIdentitasPengantarPasien\KartuIdentitasPengantarPasienResource::class,
            'route_name' => 'pendaftaran.rest.kartu-identitas-pengantar-pasien',
            'route_identifier_name' => 'kartu_identitas_pengantar_pasien_id',
            'collection_name' => 'kartu_identitas_pengantar_pasien',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'JENIS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\KartuIdentitasPengantarPasien\KartuIdentitasPengantarPasienEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\KartuIdentitasPengantarPasien\KartuIdentitasPengantarPasienCollection::class,
            'service_name' => 'KartuIdentitasPengantarPasien',
        ],
        'Pendaftaran\\V1\\Rest\\KontakPengantarPasien\\Controller' => [
            'listener' => \Pendaftaran\V1\Rest\KontakPengantarPasien\KontakPengantarPasienResource::class,
            'route_name' => 'pendaftaran.rest.kontak-pengantar-pasien',
            'route_identifier_name' => 'kontak_pengantar_pasien_id',
            'collection_name' => 'kontak_pengantar_pasien',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'JENIS',
                1 => 'NOMOR',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pendaftaran\V1\Rest\KontakPengantarPasien\KontakPengantarPasienEntity::class,
            'collection_class' => \Pendaftaran\V1\Rest\KontakPengantarPasien\KontakPengantarPasienCollection::class,
            'service_name' => 'KontakPengantarPasien',
        ],
    ],
    'api-tools-content-negotiation' => [
        'controllers' => [
            'Pendaftaran\\V1\\Rest\\Pendaftaran\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\PenanggungJawabPasien\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\KontakPenanggungJawab\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\KIPPenanggungJawab\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\TujuanPasien\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\SuratRujukanPasien\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\Penjamin\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\History\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\Kunjungan\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\Konsul\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\JawabanKonsul\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\Reservasi\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\Mutasi\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\AntrianRuangan\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\PembatalanKunjungan\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\PanggilanAntrianRuangan\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\PerubahanTanggalKunjungan\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\Kecelakaan\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\RujukanKeluar\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\Pemohon\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\AntrianTempatTidur\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\PengantarPasien\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\KartuIdentitasPengantarPasien\\Controller' => 'Json',
            'Pendaftaran\\V1\\Rest\\KontakPengantarPasien\\Controller' => 'Json',
        ],
        'accept_whitelist' => [
            'Pendaftaran\\V1\\Rest\\Pendaftaran\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\PenanggungJawabPasien\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\KontakPenanggungJawab\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\KIPPenanggungJawab\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\TujuanPasien\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\SuratRujukanPasien\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\Penjamin\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\History\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\Kunjungan\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\Konsul\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\JawabanKonsul\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\Reservasi\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\Mutasi\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\AntrianRuangan\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\PembatalanKunjungan\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\PanggilanAntrianRuangan\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\PerubahanTanggalKunjungan\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\Kecelakaan\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\RujukanKeluar\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\Pemohon\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\AntrianTempatTidur\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\PengantarPasien\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\KartuIdentitasPengantarPasien\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\KontakPengantarPasien\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'Pendaftaran\\V1\\Rest\\Pendaftaran\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\PenanggungJawabPasien\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\KontakPenanggungJawab\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\KIPPenanggungJawab\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\TujuanPasien\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\SuratRujukanPasien\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\Penjamin\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\History\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\Kunjungan\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\Konsul\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\JawabanKonsul\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\Reservasi\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\Mutasi\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\AntrianRuangan\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\PembatalanKunjungan\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\PanggilanAntrianRuangan\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\PerubahanTanggalKunjungan\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\Kecelakaan\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\RujukanKeluar\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\Pemohon\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\AntrianTempatTidur\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\PengantarPasien\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\KartuIdentitasPengantarPasien\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
            'Pendaftaran\\V1\\Rest\\KontakPengantarPasien\\Controller' => [
                0 => 'application/vnd.pendaftaran.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'api-tools-hal' => [
        'metadata_map' => [
            \Pendaftaran\V1\Rest\Pendaftaran\PendaftaranEntity::class => [
                'entity_identifier_name' => 'nomor',
                'route_name' => 'pendaftaran.rest.pendaftaran',
                'route_identifier_name' => 'nomor',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\Pendaftaran\PendaftaranCollection::class => [
                'entity_identifier_name' => 'nomor',
                'route_name' => 'pendaftaran.rest.pendaftaran',
                'route_identifier_name' => 'nomor',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\PenanggungJawabPasien\PenanggungJawabPasienEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.penanggung-jawab-pasien',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Pendaftaran\V1\Rest\PenanggungJawabPasien\PenanggungJawabPasienCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.penanggung-jawab-pasien',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\KontakPenanggungJawab\KontakPenanggungJawabEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.kontak-penanggung-jawab',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\KontakPenanggungJawab\KontakPenanggungJawabCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.kontak-penanggung-jawab',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\KIPPenanggungJawab\KIPPenanggungJawabEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.kip-penanggung-jawab',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\KIPPenanggungJawab\KIPPenanggungJawabCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.kip-penanggung-jawab',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\TujuanPasien\TujuanPasienEntity::class => [
                'entity_identifier_name' => 'nopen',
                'route_name' => 'pendaftaran.rest.tujuan-pasien',
                'route_identifier_name' => 'nopen',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\TujuanPasien\TujuanPasienCollection::class => [
                'entity_identifier_name' => 'nopen',
                'route_name' => 'pendaftaran.rest.tujuan-pasien',
                'route_identifier_name' => 'nopen',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\SuratRujukanPasien\SuratRujukanPasienEntity::class => [
                'entity_identifier_name' => 'norm',
                'route_name' => 'pendaftaran.rest.surat-rujukan-pasien',
                'route_identifier_name' => 'norm',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\SuratRujukanPasien\SuratRujukanPasienCollection::class => [
                'entity_identifier_name' => 'norm',
                'route_name' => 'pendaftaran.rest.surat-rujukan-pasien',
                'route_identifier_name' => 'norm',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\Penjamin\PenjaminEntity::class => [
                'entity_identifier_name' => 'nopen',
                'route_name' => 'pendaftaran.rest.penjamin',
                'route_identifier_name' => 'nopen',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\Penjamin\PenjaminCollection::class => [
                'entity_identifier_name' => 'nopen',
                'route_name' => 'pendaftaran.rest.penjamin',
                'route_identifier_name' => 'nopen',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\History\HistoryEntity::class => [
                'entity_identifier_name' => 'NORM',
                'route_name' => 'pendaftaran.rest.history',
                'route_identifier_name' => 'norm',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\History\HistoryCollection::class => [
                'entity_identifier_name' => 'NORM',
                'route_name' => 'pendaftaran.rest.history',
                'route_identifier_name' => 'norm',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\Kunjungan\KunjunganEntity::class => [
                'entity_identifier_name' => 'NOPEN',
                'route_name' => 'pendaftaran.rest.kunjungan',
                'route_identifier_name' => 'nopen',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\Kunjungan\KunjunganCollection::class => [
                'entity_identifier_name' => 'NOPEN',
                'route_name' => 'pendaftaran.rest.kunjungan',
                'route_identifier_name' => 'nopen',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\Konsul\KonsulEntity::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'pendaftaran.rest.konsul',
                'route_identifier_name' => 'nomor',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\Konsul\KonsulCollection::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'pendaftaran.rest.konsul',
                'route_identifier_name' => 'nomor',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\JawabanKonsul\JawabanKonsulEntity::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'pendaftaran.rest.jawaban-konsul',
                'route_identifier_name' => 'nomor',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\JawabanKonsul\JawabanKonsulCollection::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'pendaftaran.rest.jawaban-konsul',
                'route_identifier_name' => 'nomor',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\Reservasi\ReservasiEntity::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'pendaftaran.rest.reservasi',
                'route_identifier_name' => 'nomor',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\Reservasi\ReservasiCollection::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'pendaftaran.rest.reservasi',
                'route_identifier_name' => 'nomor',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\Mutasi\MutasiEntity::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'pendaftaran.rest.mutasi',
                'route_identifier_name' => 'nomor',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\Mutasi\MutasiCollection::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'pendaftaran.rest.mutasi',
                'route_identifier_name' => 'nomor',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\AntrianRuangan\AntrianRuanganEntity::class => [
                'entity_identifier_name' => 'RUANGAN',
                'route_name' => 'pendaftaran.rest.antrian-ruangan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\AntrianRuangan\AntrianRuanganCollection::class => [
                'entity_identifier_name' => 'RUANGAN',
                'route_name' => 'pendaftaran.rest.antrian-ruangan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\PembatalanKunjungan\PembatalanKunjunganEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pendaftaran.rest.pembatalan-kunjungan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\PembatalanKunjungan\PembatalanKunjunganCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pendaftaran.rest.pembatalan-kunjungan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\PanggilanAntrianRuangan\PanggilanAntrianRuanganEntity::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'pendaftaran.rest.panggilan-antrian-ruangan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\PanggilanAntrianRuangan\PanggilanAntrianRuanganCollection::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'pendaftaran.rest.panggilan-antrian-ruangan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\PerubahanTanggalKunjungan\PerubahanTanggalKunjunganEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pendaftaran.rest.perubahan-tanggal-kunjungan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\PerubahanTanggalKunjungan\PerubahanTanggalKunjunganCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pendaftaran.rest.perubahan-tanggal-kunjungan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\Kecelakaan\KecelakaanEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.kecelakaan',
                'route_identifier_name' => 'kecelakaan_id',
                'hydrator' => 'Laminas\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\Kecelakaan\KecelakaanCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.kecelakaan',
                'route_identifier_name' => 'kecelakaan_id',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\RujukanKeluar\RujukanKeluarEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.rujukan-keluar',
                'route_identifier_name' => 'rujukan_keluar_id',
                'hydrator' => 'Laminas\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pendaftaran\V1\Rest\RujukanKeluar\RujukanKeluarCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.rujukan-keluar',
                'route_identifier_name' => 'rujukan_keluar_id',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\Pemohon\PemohonEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pendaftaran.rest.pemohon',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Pendaftaran\V1\Rest\Pemohon\PemohonCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pendaftaran.rest.pemohon',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\AntrianTempatTidur\AntrianTempatTidurEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pendaftaran.rest.antrian-tempat-tidur',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Pendaftaran\V1\Rest\AntrianTempatTidur\AntrianTempatTidurCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pendaftaran.rest.antrian-tempat-tidur',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\PengantarPasien\PengantarPasienEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.pengantar-pasien',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Pendaftaran\V1\Rest\PengantarPasien\PengantarPasienCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.pengantar-pasien',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\KartuIdentitasPengantarPasien\KartuIdentitasPengantarPasienEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.kartu-identitas-pengantar-pasien',
                'route_identifier_name' => 'kartu_identitas_pengantar_pasien_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Pendaftaran\V1\Rest\KartuIdentitasPengantarPasien\KartuIdentitasPengantarPasienCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.kartu-identitas-pengantar-pasien',
                'route_identifier_name' => 'kartu_identitas_pengantar_pasien_id',
                'is_collection' => true,
            ],
            \Pendaftaran\V1\Rest\KontakPengantarPasien\KontakPengantarPasienEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.kontak-pengantar-pasien',
                'route_identifier_name' => 'kontak_pengantar_pasien_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Pendaftaran\V1\Rest\KontakPengantarPasien\KontakPengantarPasienCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pendaftaran.rest.kontak-pengantar-pasien',
                'route_identifier_name' => 'kontak_pengantar_pasien_id',
                'is_collection' => true,
            ],
        ],
    ],
    'controllers' => [
        'factories' => [],
    ],
    'api-tools-rpc' => [],
];
