<?php

/**
 * Configuration file generated by Laminas API Tools Admin
 *
 * The previous config file has been stored in ./config/{plugins_name}.config.old
 */
return [
	"Mutu",
	// Enter your plugin here. Example: 'PPI',
];
