-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.0.11 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for mutu
-- DROP DATABASE IF EXISTS `mutu`;
CREATE DATABASE IF NOT EXISTS `mutu` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `mutu`;

-- Dumping structure for table mutu.analisa
DROP TABLE IF EXISTS `analisa`;
CREATE TABLE IF NOT EXISTS `analisa` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INDIKATOR` int(11) NOT NULL,
  `RUANGAN` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `TANGGAL_AWAL` date DEFAULT NULL,
  `TANGGAL_AKHIR` date DEFAULT NULL,
  `ANALISA` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `OLEH` int(11) NOT NULL,
  `TANGGAL` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STATUS` int(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  KEY `STATUS` (`STATUS`),
  KEY `INDIKATOR` (`INDIKATOR`),
  KEY `RUANGAN` (`RUANGAN`),
  KEY `TANGGAL_AWAL` (`TANGGAL_AWAL`),
  KEY `TANGGAL_AKHIR` (`TANGGAL_AKHIR`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table mutu.data_dasar_indikator
DROP TABLE IF EXISTS `data_dasar_indikator`;
CREATE TABLE IF NOT EXISTS `data_dasar_indikator` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATA_INDIKATOR` int(11) NOT NULL DEFAULT '0' COMMENT 'TABLE MUTU->DATA_INDIKATOR',
  `NOREG` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
  `NORM` int(11) NOT NULL DEFAULT '0',
  `NUM` int(11) NOT NULL DEFAULT '0',
  `DENUM` int(11) NOT NULL DEFAULT '0',
  `NILAI` int(11) NOT NULL DEFAULT '0',
  `TANGGAL` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `OLEH` int(11) NOT NULL DEFAULT '0' COMMENT 'TABLE APLIKASI->PENGGUNA',
  `STATUS` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  KEY `DATA_INDIKATOR` (`DATA_INDIKATOR`),
  KEY `NOREG` (`NOREG`),
  KEY `NORM` (`NORM`),
  KEY `STATUS` (`STATUS`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1 COMMENT='menyimpan data dasar pengimputan indikator';

-- Data exporting was unselected.

-- Dumping structure for table mutu.data_indikator
DROP TABLE IF EXISTS `data_indikator`;
CREATE TABLE IF NOT EXISTS `data_indikator` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INDIKATOR` int(11) NOT NULL DEFAULT '0' COMMENT 'TABLE MUTU->INDIKATOR',
  `RUANGAN` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'TABLE MASTER->RUANGAN',
  `TANGGAL` date NOT NULL,
  `NUM` int(3) NOT NULL DEFAULT '0',
  `DENUM` int(3) NOT NULL DEFAULT '0',
  `OLEH` int(3) NOT NULL DEFAULT '0' COMMENT 'TABLE APLIKASI->PENGGUNA',
  `DATA_DASAR` smallint(1) NOT NULL DEFAULT '0' COMMENT 'APABILAH ADA DATA DASAR STATUS 1 JIKA TIDAK 0',
  `STATUS` smallint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  KEY `STATUS` (`STATUS`),
  KEY `INDIKATOR` (`INDIKATOR`),
  KEY `RUANGAN` (`RUANGAN`),
  KEY `TANGGAL` (`TANGGAL`),
  KEY `DATA_DASAR` (`DATA_DASAR`)
) ENGINE=InnoDB AUTO_INCREMENT=456 DEFAULT CHARSET=latin1 COMMENT='Menyimpan data transaksi indikator';

-- Data exporting was unselected.

-- Dumping structure for table mutu.indikator
DROP TABLE IF EXISTS `indikator`;
CREATE TABLE IF NOT EXISTS `indikator` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `KODE` char(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `NAMA` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
  `DEFINISI_OPERASIONAL` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `NUMERATOR` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `DENUMERATOR` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `PENGUKURAN` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
  `TARGET` int(3) NOT NULL DEFAULT '0',
  `STATUS` smallint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `KODE` (`KODE`),
  KEY `STATUS` (`STATUS`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1 COMMENT='Indikator';

-- Data exporting was unselected.

-- Dumping structure for table mutu.laporan
DROP TABLE IF EXISTS `laporan`;
CREATE TABLE IF NOT EXISTS `laporan` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INDIKATOR` int(11) NOT NULL,
  `RUANGAN` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `TANGGAL_AWAL` date NOT NULL,
  `TANGGAL_AKHIR` date NOT NULL,
  `JUDUL` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
  `KETERANGAN` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `FILES` longblob NOT NULL,
  `TYPE` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `OLEH` int(11) NOT NULL,
  `TANGGAL` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STATUS` int(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  KEY `STATUS` (`STATUS`),
  KEY `INDIKATOR` (`INDIKATOR`),
  KEY `RUANGAN` (`RUANGAN`),
  KEY `TANGGAL_AWAL` (`TANGGAL_AWAL`),
  KEY `TANGGAL_AKHIR` (`TANGGAL_AKHIR`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table mutu.pdsa
DROP TABLE IF EXISTS `pdsa`;
CREATE TABLE IF NOT EXISTS `pdsa` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ANALISA` int(11) NOT NULL DEFAULT '0',
  `PLAN` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `DO` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `STUDY` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `ACTION` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `OLEH` int(11) NOT NULL,
  `TANGGAL` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STATUS` int(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  KEY `STATUS` (`STATUS`),
  KEY `ANALISA` (`ANALISA`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table mutu.ruangan_indikator
DROP TABLE IF EXISTS `ruangan_indikator`;
CREATE TABLE IF NOT EXISTS `ruangan_indikator` (
  `RUANGAN` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'TABLE MASTER->RUANGAN',
  `INDIKATOR` int(11) NOT NULL DEFAULT '0' COMMENT 'TABLE MUTU->INDIKATOR',
  `STATUS` smallint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`RUANGAN`,`INDIKATOR`),
  KEY `STATUS` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Mapping Indikator dan Ruangan';

-- Data exporting was unselected.

-- Dumping structure for procedure mutu.cetakAnalisaDanPDSA
DROP PROCEDURE IF EXISTS `cetakAnalisaDanPDSA`;
DELIMITER //
CREATE PROCEDURE `cetakAnalisaDanPDSA`(
	IN `PINDIKATOR` INT
,
	IN `PRUANGAN` CHAR(20)
,
	IN `PTGL_AWAL` VARCHAR(50),
	IN `PTGL_AKHIR` VARCHAR(50)








)
BEGIN
	SET @idanalisa = null;
	SET @deskpds = null;
	SET @numan = 0;
	SET @numpdsa = 0;
	
	SELECT 
		IF(@idanalisa = an.ID, '' , @numan := @numan + 1) NO_ANALISA,
		IF(@idanalisa = an.ID, '', @desk:= an.ANALISA) ANALISA,
		IF(@idanalisa = an.ID, '', CONCAT('P.Awal : ',an.TANGGAL_AWAL,' P.Akhir : ',an.TANGGAL_AKHIR)) PERIODE,
		IF(@deskpds = pd.ID , '', IF(@idanalisa = an.ID, @numpdsa := @numpdsa + 1 , @numpdsa := 1)) NO_PDSA,
		IF(@idanalisa = an.ID, @idanalisa, @idanalisa:= an.ID) ID_ANALISA,
		IF(@deskpds = pd.ID, @deskpds, @deskpds := pd.ID) IDPDSA, 
		pd.PLAN,
		pd.`DO`,
		pd.STUDY,
		pd.`ACTION` 
	FROM 
		mutu.analisa an
	LEFT JOIN 
		mutu.pdsa pd ON pd.ANALISA = an.ID
	WHERE an.INDIKATOR = PINDIKATOR
	AND an.RUANGAN = PRUANGAN
	AND an.TANGGAL_AWAL >= PTGL_AWAL
	AND an.TANGGAL_AKHIR <= PTGL_AKHIR
	AND an.`STATUS` = 1
	;
END//
DELIMITER ;

-- Dumping structure for procedure mutu.DataGrafikIndikatorMutu
DROP PROCEDURE IF EXISTS `DataGrafikIndikatorMutu`;
DELIMITER //
CREATE PROCEDURE `DataGrafikIndikatorMutu`(
	IN `PINDIKATOR` INT,
	IN `PRUANGAN` CHAR(20),
	IN `PTGL_AWAL` VARCHAR(50),
	IN `PTGL_AKHIR` VARCHAR(50)











)
BEGIN
	DECLARE VBULANT INT DEFAULT 0;
	DECLARE VCOUNT DECIMAL(10,2) DEFAULT 0;
	
	SELECT
		COUNT(*) INTO VBULANT
	FROM (
		SELECT 
			DATE_FORMAT(di.TANGGAL,'%Y-%m') GROUP_BULAN
		FROM master.tanggal di
		WHERE di.TANGGAL BETWEEN PTGL_AWAL AND PTGL_AKHIR
		GROUP BY DATE_FORMAT(di.TANGGAL,'%Y-%m')
	)tgl;
	
	SELECT SUM(t.REALISASI) INTO VCOUNT
	FROM (
		SELECT 
				(SUM(di.NUM) / SUM(di.DENUM)) * 100 REALISASI
		FROM mutu.data_indikator di
		WHERE di.INDIKATOR = PINDIKATOR 
		AND di.RUANGAN LIKE CONCAT(PRUANGAN,'%')
		AND di.TANGGAL BETWEEN PTGL_AWAL AND PTGL_AKHIR
		AND di.`STATUS` = 1
		GROUP BY DATE_FORMAT(di.TANGGAL,'%Y-%m')
	)t;
	
	SELECT
		i.ID ID_INDIKATOR,
		CONCAT(i.KODE,' - ', i.NAMA) DESK_INDIKATOR,
		tgl.GROUP_BULAN,
		ru.ID ID_RUANGAN,
		ru.DESKRIPSI DESK_RUANGAN,
		IF(dt_in.T_NUM IS NULL, 0, dt_in.T_NUM) T_NUM,
		IF(dt_in.T_DENUM IS NULL, 0, dt_in.T_DENUM) T_DENUM,	
		IF(dt_in.REALISASI IS NULL, 0, dt_in.REALISASI) REALISASI,
		IF(ROUND(VCOUNT / VBULANT,2) IS NULL, 0, ROUND(VCOUNT / VBULANT,2)) RATA_RATA,
		i.TARGET
	FROM (
		SELECT 
			DATE_FORMAT(di.TANGGAL,'%Y-%m') GROUP_BULAN
		FROM master.tanggal di
		WHERE di.TANGGAL BETWEEN PTGL_AWAL AND PTGL_AKHIR
		GROUP BY DATE_FORMAT(di.TANGGAL,'%Y-%m')
	)tgl 
	LEFT JOIN (
		SELECT 
			DATE_FORMAT(di.TANGGAL,'%Y-%m') GROUP_BULAN,
			di.RUANGAN,
			SUM(di.NUM) T_NUM,
			SUM(di.DENUM) T_DENUM,
			ROUND((SUM(di.NUM) / SUM(di.DENUM)) * 100, 2) REALISASI,
			di.INDIKATOR
		FROM mutu.data_indikator di
		WHERE di.INDIKATOR = PINDIKATOR 
		AND di.RUANGAN LIKE CONCAT(PRUANGAN,'%')
		AND di.TANGGAL BETWEEN PTGL_AWAL AND PTGL_AKHIR
		AND di.`STATUS` = 1
		GROUP BY DATE_FORMAT(di.TANGGAL,'%Y-%m')
	) dt_in ON dt_in.GROUP_BULAN = tgl.GROUP_BULAN
	,(SELECT 
			* 
		FROM mutu.indikator i WHERE i.ID = PINDIKATOR) i
	,(SELECT 
			* 
		FROM master.ruangan ru WHERE ru.ID = PRUANGAN) ru
	GROUP BY tgl.GROUP_BULAN; 

END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
