USE aplikasi;
INSERT INTO aplikasi.`modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`) VALUES ('32', 'MUTU', 1, '', 1, NULL, NULL, 0);
INSERT INTO aplikasi.`modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`) VALUES ('3201', 'PENGATURAN', 2, 'Pengaturan', 1, NULL, 'x-fa fa-cogs', 1);
INSERT INTO aplikasi.`modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`) VALUES ('320101', 'INDIKATOR', 3, 'Indikator Mutu', 1, 'mutu.indikator.Wokrspace', 'x-fa fa-book', 0);
INSERT INTO aplikasi.`modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`) VALUES ('320102', 'INDIKATOR RUANGAN', 3, 'Indikator Ruangan', 1, 'mutu.indikator.ruangan.Workspace', 'x-fa fa-th-list', 0);
INSERT INTO aplikasi.`modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`) VALUES ('3202', 'INPUT DATA INDIKATOR', 2, 'Data Indikator', 1, 'mutu.indikator.data.Worksapce', 'x-fa fa-table', 0);
INSERT INTO aplikasi.`modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`) VALUES ('3203', 'TINDAK LANJUT', 2, 'Tindak Lanjut', 1, 'mutu.indikator.tindaklanjut.Workspace', 'x-fa fa-archive', 0);
INSERT INTO aplikasi.`modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`) VALUES ('320301', 'ANALISA', 3, '', 1, NULL, NULL, 0);
INSERT INTO aplikasi.`modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`) VALUES ('320302', 'PDSA', 3, '', 1, NULL, NULL, 0);
INSERT INTO aplikasi.`modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`) VALUES ('320303', 'LAPORAN & BALASAN', 3, '', 1, NULL, NULL, 0);
