USE aplikasi;

REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`) VALUES ('10070101', 'UPDATE STATUS PASIEN', 4, '', 1, NULL, NULL, 0, 0, NULL);