<?php
return [
    'service_manager' => [
        'factories' => [
            \PPI\V1\Rest\Kegiatan\KegiatanResource::class => \PPI\V1\Rest\Kegiatan\KegiatanResourceFactory::class,
            \PPI\V1\Rest\GroupEvaluasi\GroupEvaluasiResource::class => \PPI\V1\Rest\GroupEvaluasi\GroupEvaluasiResourceFactory::class,
            \PPI\V1\Rest\KegiatanGroup\KegiatanGroupResource::class => \PPI\V1\Rest\KegiatanGroup\KegiatanGroupResourceFactory::class,
            \PPI\V1\Rest\PenilaianKegiatan\PenilaianKegiatanResource::class => \PPI\V1\Rest\PenilaianKegiatan\PenilaianKegiatanResourceFactory::class,
            \PPI\V1\Rest\PenilaianKegiatanDetail\PenilaianKegiatanDetailResource::class => \PPI\V1\Rest\PenilaianKegiatanDetail\PenilaianKegiatanDetailResourceFactory::class,
            \PPI\V1\Rest\IDO\IDOResource::class => \PPI\V1\Rest\IDO\IDOResourceFactory::class,
            \PPI\V1\Rest\TertusukJarum\TertusukJarumResource::class => \PPI\V1\Rest\TertusukJarum\TertusukJarumResourceFactory::class,
            \PPI\V1\Rest\CuciTangan\CuciTanganResource::class => \PPI\V1\Rest\CuciTangan\CuciTanganResourceFactory::class,
            \PPI\V1\Rest\CuciTanganDetail\CuciTanganDetailResource::class => \PPI\V1\Rest\CuciTanganDetail\CuciTanganDetailResourceFactory::class,
            \PPI\V1\Rest\Kelompok\KelompokResource::class => \PPI\V1\Rest\Kelompok\KelompokResourceFactory::class,
            \PPI\V1\Rest\PenilaianKegiatanHarian\PenilaianKegiatanHarianResource::class => \PPI\V1\Rest\PenilaianKegiatanHarian\PenilaianKegiatanHarianResourceFactory::class,
            \PPI\V1\Rest\PenilaianKegiatanHarianDetail\PenilaianKegiatanHarianDetailResource::class => \PPI\V1\Rest\PenilaianKegiatanHarianDetail\PenilaianKegiatanHarianDetailResourceFactory::class,
            \PPI\V1\Rest\LimbahInfeksius\LimbahInfeksiusResource::class => \PPI\V1\Rest\LimbahInfeksius\LimbahInfeksiusResourceFactory::class,
            \PPI\V1\Rest\Alasan\AlasanResource::class => \PPI\V1\Rest\Alasan\AlasanResourceFactory::class,
            \PPI\V1\Rest\KegiatanAlasan\KegiatanAlasanResource::class => \PPI\V1\Rest\KegiatanAlasan\KegiatanAlasanResourceFactory::class,
            \PPI\V1\Rest\AuditIndividu\AuditIndividuResource::class => \PPI\V1\Rest\AuditIndividu\AuditIndividuResourceFactory::class,
            \PPI\V1\Rest\XampleIndividu\XampleIndividuResource::class => \PPI\V1\Rest\XampleIndividu\XampleIndividuResourceFactory::class,
            \PPI\V1\Rest\XampelDetail\XampelDetailResource::class => \PPI\V1\Rest\XampelDetail\XampelDetailResourceFactory::class,
            \PPI\V1\Rest\GejalaIdo\GejalaIdoResource::class => \PPI\V1\Rest\GejalaIdo\GejalaIdoResourceFactory::class,
            \PPI\V1\Rest\TindakLanjut\TindakLanjutResource::class => \PPI\V1\Rest\TindakLanjut\TindakLanjutResourceFactory::class,
            \PPI\V1\Rest\Flebitis\FlebitisResource::class => \PPI\V1\Rest\Flebitis\FlebitisResourceFactory::class,
            \PPI\V1\Rest\Vap\VapResource::class => \PPI\V1\Rest\Vap\VapResourceFactory::class,
            \PPI\V1\Rest\ISK\ISKResource::class => \PPI\V1\Rest\ISK\ISKResourceFactory::class,
        ],
    ],
    'router' => [
        'routes' => [
            'ppi.rest.kegiatan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/kegiatan[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\Kegiatan\\Controller',
                    ],
                ],
            ],
            'ppi.rest.group-evaluasi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/groupevaluasi[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\GroupEvaluasi\\Controller',
                    ],
                ],
            ],
            'ppi.rest.kegiatan-group' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/kegiatan/group[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\KegiatanGroup\\Controller',
                    ],
                ],
            ],
            'ppi.rest.penilaian-kegiatan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/penilaiankegiatan[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\PenilaianKegiatan\\Controller',
                    ],
                ],
            ],
            'ppi.rest.penilaian-kegiatan-detail' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/penilaiankegiatan/detail[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\PenilaianKegiatanDetail\\Controller',
                    ],
                ],
            ],
            'ppi.rest.ido' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/ido[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\IDO\\Controller',
                    ],
                ],
            ],
            'ppi.rest.tertusuk-jarum' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/tertusukjarum[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\TertusukJarum\\Controller',
                    ],
                ],
            ],
            'ppi.rest.cuci-tangan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/cucitangan[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\CuciTangan\\Controller',
                    ],
                ],
            ],
            'ppi.rest.cuci-tangan-detail' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/cucitangan/detail[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\CuciTanganDetail\\Controller',
                    ],
                ],
            ],
            'ppi.rest.kelompok' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/kelompok[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\Kelompok\\Controller',
                    ],
                ],
            ],
            'ppi.rest.penilaian-kegiatan-harian' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/penilaian/kegiatanharian[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\PenilaianKegiatanHarian\\Controller',
                    ],
                ],
            ],
            'ppi.rest.penilaian-kegiatan-harian-detail' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/penilaian/kegiatanharian/detail[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\PenilaianKegiatanHarianDetail\\Controller',
                    ],
                ],
            ],
            'ppi.rest.limbah-infeksius' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/limbahinfeksius[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\LimbahInfeksius\\Controller',
                    ],
                ],
            ],
            'ppi.rest.alasan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/alasan[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\Alasan\\Controller',
                    ],
                ],
            ],
            'ppi.rest.kegiatan-alasan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/kegiatan/alasan[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\KegiatanAlasan\\Controller',
                    ],
                ],
            ],
            'ppi.rest.audit-individu' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/audit/individu[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\AuditIndividu\\Controller',
                    ],
                ],
            ],
            'ppi.rest.xample-individu' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/xampleindividu[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\XampleIndividu\\Controller',
                    ],
                ],
            ],
            'ppi.rest.xampel-detail' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/xample/detail[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\XampelDetail\\Controller',
                    ],
                ],
            ],
            'ppi.rest.gejala-ido' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/gejalaido[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\GejalaIdo\\Controller',
                    ],
                ],
            ],
            'ppi.rest.tindak-lanjut' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/tindaklanjut[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\TindakLanjut\\Controller',
                    ],
                ],
            ],
            'ppi.rest.flebitis' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/hais/flebitis[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\Flebitis\\Controller',
                    ],
                ],
            ],
            'ppi.rest.vap' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/hais/vap[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\Vap\\Controller',
                    ],
                ],
            ],
            'ppi.rest.isk' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ppi/hais/isk[/:id]',
                    'defaults' => [
                        'controller' => 'PPI\\V1\\Rest\\ISK\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'api-tools-versioning' => [
        'uri' => [
            0 => 'ppi.rest.kegiatan',
            1 => 'ppi.rest.group-evaluasi',
            2 => 'ppi.rest.kegiatan-group',
            3 => 'ppi.rest.penilaian-kegiatan',
            4 => 'ppi.rest.penilaian-kegiatan-detail',
            5 => 'ppi.rest.ido',
            6 => 'ppi.rest.tertusuk-jarum',
            7 => 'ppi.rest.cuci-tangan',
            8 => 'ppi.rest.cuci-tangan-detail',
            9 => 'ppi.rest.kelompok',
            10 => 'ppi.rest.penilaian-kegiatan-harian',
            11 => 'ppi.rest.penilaian-kegiatan-harian-detail',
            12 => 'ppi.rest.limbah-infeksius',
            13 => 'ppi.rest.alasan',
            14 => 'ppi.rest.kegiatan-alasan',
            15 => 'ppi.rest.audit-individu',
            16 => 'ppi.rest.xample-individu',
            17 => 'ppi.rest.xampel-detail',
            18 => 'ppi.rest.gejala-ido',
            19 => 'ppi.rest.tindak-lanjut',
            20 => 'ppi.rest.flebitis',
            21 => 'ppi.rest.vap',
            22 => 'ppi.rest.isk',
        ],
    ],
    'api-tools-rest' => [
        'PPI\\V1\\Rest\\Kegiatan\\Controller' => [
            'listener' => \PPI\V1\Rest\Kegiatan\KegiatanResource::class,
            'route_name' => 'ppi.rest.kegiatan',
            'route_identifier_name' => 'id',
            'collection_name' => 'kegiatan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
                1 => 'ID',
                2 => 'DESKRIPSI',
                3 => 'start',
                4 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\Kegiatan\KegiatanEntity::class,
            'collection_class' => \PPI\V1\Rest\Kegiatan\KegiatanCollection::class,
            'service_name' => 'Kegiatan',
        ],
        'PPI\\V1\\Rest\\GroupEvaluasi\\Controller' => [
            'listener' => \PPI\V1\Rest\GroupEvaluasi\GroupEvaluasiResource::class,
            'route_name' => 'ppi.rest.group-evaluasi',
            'route_identifier_name' => 'id',
            'collection_name' => 'group_evaluasi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
                1 => 'ID',
                2 => 'JENIS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\GroupEvaluasi\GroupEvaluasiEntity::class,
            'collection_class' => \PPI\V1\Rest\GroupEvaluasi\GroupEvaluasiCollection::class,
            'service_name' => 'GroupEvaluasi',
        ],
        'PPI\\V1\\Rest\\KegiatanGroup\\Controller' => [
            'listener' => \PPI\V1\Rest\KegiatanGroup\KegiatanGroupResource::class,
            'route_name' => 'ppi.rest.kegiatan-group',
            'route_identifier_name' => 'id',
            'collection_name' => 'kegiatan_group',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
                1 => 'KEGIATAN',
                2 => 'GROUP',
                3 => 'ID',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\KegiatanGroup\KegiatanGroupEntity::class,
            'collection_class' => \PPI\V1\Rest\KegiatanGroup\KegiatanGroupCollection::class,
            'service_name' => 'KegiatanGroup',
        ],
        'PPI\\V1\\Rest\\PenilaianKegiatan\\Controller' => [
            'listener' => \PPI\V1\Rest\PenilaianKegiatan\PenilaianKegiatanResource::class,
            'route_name' => 'ppi.rest.penilaian-kegiatan',
            'route_identifier_name' => 'id',
            'collection_name' => 'penilaian_kegiatan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
                1 => 'RUANGAN',
                2 => 'GROUP',
                3 => 'ID',
                4 => 'USER',
                5 => 'start',
                6 => 'limit',
                7 => 'TANGGAL_BUAT',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\PenilaianKegiatan\PenilaianKegiatanEntity::class,
            'collection_class' => \PPI\V1\Rest\PenilaianKegiatan\PenilaianKegiatanCollection::class,
            'service_name' => 'PenilaianKegiatan',
        ],
        'PPI\\V1\\Rest\\PenilaianKegiatanDetail\\Controller' => [
            'listener' => \PPI\V1\Rest\PenilaianKegiatanDetail\PenilaianKegiatanDetailResource::class,
            'route_name' => 'ppi.rest.penilaian-kegiatan-detail',
            'route_identifier_name' => 'id',
            'collection_name' => 'penilaian_kegiatan_detail',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
                1 => 'PENILAIAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\PenilaianKegiatanDetail\PenilaianKegiatanDetailEntity::class,
            'collection_class' => \PPI\V1\Rest\PenilaianKegiatanDetail\PenilaianKegiatanDetailCollection::class,
            'service_name' => 'PenilaianKegiatanDetail',
        ],
        'PPI\\V1\\Rest\\IDO\\Controller' => [
            'listener' => \PPI\V1\Rest\IDO\IDOResource::class,
            'route_name' => 'ppi.rest.ido',
            'route_identifier_name' => 'id',
            'collection_name' => 'ido',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
                1 => 'ID',
                2 => 'ID_OPERASI',
                3 => 'start',
                4 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\IDO\IDOEntity::class,
            'collection_class' => \PPI\V1\Rest\IDO\IDOCollection::class,
            'service_name' => 'IDO',
        ],
        'PPI\\V1\\Rest\\TertusukJarum\\Controller' => [
            'listener' => \PPI\V1\Rest\TertusukJarum\TertusukJarumResource::class,
            'route_name' => 'ppi.rest.tertusuk-jarum',
            'route_identifier_name' => 'id',
            'collection_name' => 'tertusuk_jarum',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
                1 => 'start',
                2 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\TertusukJarum\TertusukJarumEntity::class,
            'collection_class' => \PPI\V1\Rest\TertusukJarum\TertusukJarumCollection::class,
            'service_name' => 'TertusukJarum',
        ],
        'PPI\\V1\\Rest\\CuciTangan\\Controller' => [
            'listener' => \PPI\V1\Rest\CuciTangan\CuciTanganResource::class,
            'route_name' => 'ppi.rest.cuci-tangan',
            'route_identifier_name' => 'id',
            'collection_name' => 'cuci_tangan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\CuciTangan\CuciTanganEntity::class,
            'collection_class' => \PPI\V1\Rest\CuciTangan\CuciTanganCollection::class,
            'service_name' => 'CuciTangan',
        ],
        'PPI\\V1\\Rest\\CuciTanganDetail\\Controller' => [
            'listener' => \PPI\V1\Rest\CuciTanganDetail\CuciTanganDetailResource::class,
            'route_name' => 'ppi.rest.cuci-tangan-detail',
            'route_identifier_name' => 'id',
            'collection_name' => 'cuci_tangan_detail',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
                1 => 'CUCI_TANGAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\CuciTanganDetail\CuciTanganDetailEntity::class,
            'collection_class' => \PPI\V1\Rest\CuciTanganDetail\CuciTanganDetailCollection::class,
            'service_name' => 'CuciTanganDetail',
        ],
        'PPI\\V1\\Rest\\Kelompok\\Controller' => [
            'listener' => \PPI\V1\Rest\Kelompok\KelompokResource::class,
            'route_name' => 'ppi.rest.kelompok',
            'route_identifier_name' => 'id',
            'collection_name' => 'kelompok',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\Kelompok\KelompokEntity::class,
            'collection_class' => \PPI\V1\Rest\Kelompok\KelompokCollection::class,
            'service_name' => 'Kelompok',
        ],
        'PPI\\V1\\Rest\\PenilaianKegiatanHarian\\Controller' => [
            'listener' => \PPI\V1\Rest\PenilaianKegiatanHarian\PenilaianKegiatanHarianResource::class,
            'route_name' => 'ppi.rest.penilaian-kegiatan-harian',
            'route_identifier_name' => 'id',
            'collection_name' => 'penilaian_kegiatan_harian',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
                1 => 'GROUP',
                2 => 'RUANGAN',
                3 => 'ID',
                4 => 'USER',
                5 => 'start',
                6 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\PenilaianKegiatanHarian\PenilaianKegiatanHarianEntity::class,
            'collection_class' => \PPI\V1\Rest\PenilaianKegiatanHarian\PenilaianKegiatanHarianCollection::class,
            'service_name' => 'PenilaianKegiatanHarian',
        ],
        'PPI\\V1\\Rest\\PenilaianKegiatanHarianDetail\\Controller' => [
            'listener' => \PPI\V1\Rest\PenilaianKegiatanHarianDetail\PenilaianKegiatanHarianDetailResource::class,
            'route_name' => 'ppi.rest.penilaian-kegiatan-harian-detail',
            'route_identifier_name' => 'id',
            'collection_name' => 'penilaian_kegiatan_harian_detail',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'PK_HARIAN',
                1 => 'MINGGU',
                2 => 'HARIAN',
                3 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\PenilaianKegiatanHarianDetail\PenilaianKegiatanHarianDetailEntity::class,
            'collection_class' => \PPI\V1\Rest\PenilaianKegiatanHarianDetail\PenilaianKegiatanHarianDetailCollection::class,
            'service_name' => 'PenilaianKegiatanHarianDetail',
        ],
        'PPI\\V1\\Rest\\LimbahInfeksius\\Controller' => [
            'listener' => \PPI\V1\Rest\LimbahInfeksius\LimbahInfeksiusResource::class,
            'route_name' => 'ppi.rest.limbah-infeksius',
            'route_identifier_name' => 'id',
            'collection_name' => 'limbah_infeksius',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
                1 => 'KATEGORI',
                2 => 'RUANGAN',
                3 => 'start',
                4 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\LimbahInfeksius\LimbahInfeksiusEntity::class,
            'collection_class' => \PPI\V1\Rest\LimbahInfeksius\LimbahInfeksiusCollection::class,
            'service_name' => 'LimbahInfeksius',
        ],
        'PPI\\V1\\Rest\\Alasan\\Controller' => [
            'listener' => \PPI\V1\Rest\Alasan\AlasanResource::class,
            'route_name' => 'ppi.rest.alasan',
            'route_identifier_name' => 'id',
            'collection_name' => 'alasan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
                1 => 'ID',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\Alasan\AlasanEntity::class,
            'collection_class' => \PPI\V1\Rest\Alasan\AlasanCollection::class,
            'service_name' => 'Alasan',
        ],
        'PPI\\V1\\Rest\\KegiatanAlasan\\Controller' => [
            'listener' => \PPI\V1\Rest\KegiatanAlasan\KegiatanAlasanResource::class,
            'route_name' => 'ppi.rest.kegiatan-alasan',
            'route_identifier_name' => 'id',
            'collection_name' => 'kegiatan_alasan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KEGIATAN',
                1 => 'STATUS',
                2 => 'ID',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\KegiatanAlasan\KegiatanAlasanEntity::class,
            'collection_class' => \PPI\V1\Rest\KegiatanAlasan\KegiatanAlasanCollection::class,
            'service_name' => 'KegiatanAlasan',
        ],
        'PPI\\V1\\Rest\\AuditIndividu\\Controller' => [
            'listener' => \PPI\V1\Rest\AuditIndividu\AuditIndividuResource::class,
            'route_name' => 'ppi.rest.audit-individu',
            'route_identifier_name' => 'id',
            'collection_name' => 'audit_individu',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'PROFESI',
                1 => 'STATUS',
                2 => 'GROUP',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\AuditIndividu\AuditIndividuEntity::class,
            'collection_class' => \PPI\V1\Rest\AuditIndividu\AuditIndividuCollection::class,
            'service_name' => 'AuditIndividu',
        ],
        'PPI\\V1\\Rest\\XampleIndividu\\Controller' => [
            'listener' => \PPI\V1\Rest\XampleIndividu\XampleIndividuResource::class,
            'route_name' => 'ppi.rest.xample-individu',
            'route_identifier_name' => 'id',
            'collection_name' => 'xample_individu',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
                1 => 'PERIODE',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\XampleIndividu\XampleIndividuEntity::class,
            'collection_class' => \PPI\V1\Rest\XampleIndividu\XampleIndividuCollection::class,
            'service_name' => 'XampleIndividu',
        ],
        'PPI\\V1\\Rest\\XampelDetail\\Controller' => [
            'listener' => \PPI\V1\Rest\XampelDetail\XampelDetailResource::class,
            'route_name' => 'ppi.rest.xampel-detail',
            'route_identifier_name' => 'id',
            'collection_name' => 'xampel_detail',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'XAMPLE',
                1 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\XampelDetail\XampelDetailEntity::class,
            'collection_class' => \PPI\V1\Rest\XampelDetail\XampelDetailCollection::class,
            'service_name' => 'XampelDetail',
        ],
        'PPI\\V1\\Rest\\GejalaIdo\\Controller' => [
            'listener' => \PPI\V1\Rest\GejalaIdo\GejalaIdoResource::class,
            'route_name' => 'ppi.rest.gejala-ido',
            'route_identifier_name' => 'id',
            'collection_name' => 'gejala_ido',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'IDO',
                1 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\GejalaIdo\GejalaIdoEntity::class,
            'collection_class' => \PPI\V1\Rest\GejalaIdo\GejalaIdoCollection::class,
            'service_name' => 'GejalaIdo',
        ],
        'PPI\\V1\\Rest\\TindakLanjut\\Controller' => [
            'listener' => \PPI\V1\Rest\TindakLanjut\TindakLanjutResource::class,
            'route_name' => 'ppi.rest.tindak-lanjut',
            'route_identifier_name' => 'id',
            'collection_name' => 'tindak_lanjut',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'GROUP',
                1 => 'TAHUN',
                2 => 'BULAN',
                3 => 'start',
                4 => 'limit',
                5 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\TindakLanjut\TindakLanjutEntity::class,
            'collection_class' => \PPI\V1\Rest\TindakLanjut\TindakLanjutCollection::class,
            'service_name' => 'TindakLanjut',
        ],
        'PPI\\V1\\Rest\\Flebitis\\Controller' => [
            'listener' => \PPI\V1\Rest\Flebitis\FlebitisResource::class,
            'route_name' => 'ppi.rest.flebitis',
            'route_identifier_name' => 'id',
            'collection_name' => 'flebitis',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'NOPEN',
                2 => 'STATUS',
                3 => 'NORM',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\Flebitis\FlebitisEntity::class,
            'collection_class' => \PPI\V1\Rest\Flebitis\FlebitisCollection::class,
            'service_name' => 'Flebitis',
        ],
        'PPI\\V1\\Rest\\Vap\\Controller' => [
            'listener' => \PPI\V1\Rest\Vap\VapResource::class,
            'route_name' => 'ppi.rest.vap',
            'route_identifier_name' => 'id',
            'collection_name' => 'vap',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'NOPEN',
                2 => 'RUANGAN',
                3 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\Vap\VapEntity::class,
            'collection_class' => \PPI\V1\Rest\Vap\VapCollection::class,
            'service_name' => 'vap',
        ],
        'PPI\\V1\\Rest\\ISK\\Controller' => [
            'listener' => \PPI\V1\Rest\ISK\ISKResource::class,
            'route_name' => 'ppi.rest.isk',
            'route_identifier_name' => 'id',
            'collection_name' => 'isk',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'NOPEN',
                2 => 'NORM',
                3 => 'RUANGAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \PPI\V1\Rest\ISK\ISKEntity::class,
            'collection_class' => \PPI\V1\Rest\ISK\ISKCollection::class,
            'service_name' => 'ISK',
        ],
    ],
    'api-tools-content-negotiation' => [
        'controllers' => [
            'PPI\\V1\\Rest\\Kegiatan\\Controller' => 'Json',
            'PPI\\V1\\Rest\\GroupEvaluasi\\Controller' => 'Json',
            'PPI\\V1\\Rest\\KegiatanGroup\\Controller' => 'Json',
            'PPI\\V1\\Rest\\PenilaianKegiatan\\Controller' => 'Json',
            'PPI\\V1\\Rest\\PenilaianKegiatanDetail\\Controller' => 'Json',
            'PPI\\V1\\Rest\\IDO\\Controller' => 'Json',
            'PPI\\V1\\Rest\\TertusukJarum\\Controller' => 'Json',
            'PPI\\V1\\Rest\\CuciTangan\\Controller' => 'Json',
            'PPI\\V1\\Rest\\CuciTanganDetail\\Controller' => 'Json',
            'PPI\\V1\\Rest\\Kelompok\\Controller' => 'Json',
            'PPI\\V1\\Rest\\PenilaianKegiatanHarian\\Controller' => 'Json',
            'PPI\\V1\\Rest\\PenilaianKegiatanHarianDetail\\Controller' => 'Json',
            'PPI\\V1\\Rest\\LimbahInfeksius\\Controller' => 'Json',
            'PPI\\V1\\Rest\\Alasan\\Controller' => 'Json',
            'PPI\\V1\\Rest\\KegiatanAlasan\\Controller' => 'Json',
            'PPI\\V1\\Rest\\AuditIndividu\\Controller' => 'Json',
            'PPI\\V1\\Rest\\XampleIndividu\\Controller' => 'Json',
            'PPI\\V1\\Rest\\XampelDetail\\Controller' => 'Json',
            'PPI\\V1\\Rest\\GejalaIdo\\Controller' => 'Json',
            'PPI\\V1\\Rest\\TindakLanjut\\Controller' => 'Json',
            'PPI\\V1\\Rest\\Flebitis\\Controller' => 'Json',
            'PPI\\V1\\Rest\\Vap\\Controller' => 'Json',
            'PPI\\V1\\Rest\\ISK\\Controller' => 'Json',
        ],
        'accept_whitelist' => [
            'PPI\\V1\\Rest\\Kegiatan\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\GroupEvaluasi\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\KegiatanGroup\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\PenilaianKegiatan\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\PenilaianKegiatanDetail\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\IDO\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\TertusukJarum\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\CuciTangan\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\CuciTanganDetail\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\Kelompok\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\PenilaianKegiatanHarian\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\PenilaianKegiatanHarianDetail\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\LimbahInfeksius\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\Alasan\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\KegiatanAlasan\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\AuditIndividu\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\XampleIndividu\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\XampelDetail\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\GejalaIdo\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\TindakLanjut\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\Flebitis\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\Vap\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'PPI\\V1\\Rest\\ISK\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'PPI\\V1\\Rest\\Kegiatan\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\GroupEvaluasi\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\KegiatanGroup\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\PenilaianKegiatan\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\PenilaianKegiatanDetail\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\IDO\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\TertusukJarum\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\CuciTangan\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\CuciTanganDetail\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\Kelompok\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\PenilaianKegiatanHarian\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\PenilaianKegiatanHarianDetail\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\LimbahInfeksius\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\Alasan\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\KegiatanAlasan\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\AuditIndividu\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\XampleIndividu\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\XampelDetail\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\GejalaIdo\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\TindakLanjut\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\Flebitis\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\Vap\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
            'PPI\\V1\\Rest\\ISK\\Controller' => [
                0 => 'application/vnd.ppi.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'api-tools-hal' => [
        'metadata_map' => [
            \PPI\V1\Rest\Kegiatan\KegiatanEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.kegiatan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\Kegiatan\KegiatanCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.kegiatan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\GroupEvaluasi\GroupEvaluasiEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.group-evaluasi',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\GroupEvaluasi\GroupEvaluasiCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.group-evaluasi',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\KegiatanGroup\KegiatanGroupEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.kegiatan-group',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\KegiatanGroup\KegiatanGroupCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.kegiatan-group',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\PenilaianKegiatan\PenilaianKegiatanEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.penilaian-kegiatan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\PenilaianKegiatan\PenilaianKegiatanCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.penilaian-kegiatan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\PenilaianKegiatanDetail\PenilaianKegiatanDetailEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.penilaian-kegiatan-detail',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\PenilaianKegiatanDetail\PenilaianKegiatanDetailCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.penilaian-kegiatan-detail',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\IDO\IDOEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.ido',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\IDO\IDOCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.ido',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\TertusukJarum\TertusukJarumEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.tertusuk-jarum',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\TertusukJarum\TertusukJarumCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.tertusuk-jarum',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\CuciTangan\CuciTanganEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.cuci-tangan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\CuciTangan\CuciTanganCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.cuci-tangan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\CuciTanganDetail\CuciTanganDetailEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.cuci-tangan-detail',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\CuciTanganDetail\CuciTanganDetailCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.cuci-tangan-detail',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\Kelompok\KelompokEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.kelompok',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\Kelompok\KelompokCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.kelompok',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\PenilaianKegiatanHarian\PenilaianKegiatanHarianEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.penilaian-kegiatan-harian',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\PenilaianKegiatanHarian\PenilaianKegiatanHarianCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.penilaian-kegiatan-harian',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\PenilaianKegiatanHarianDetail\PenilaianKegiatanHarianDetailEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.penilaian-kegiatan-harian-detail',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\PenilaianKegiatanHarianDetail\PenilaianKegiatanHarianDetailCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.penilaian-kegiatan-harian-detail',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\LimbahInfeksius\LimbahInfeksiusEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.limbah-infeksius',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\LimbahInfeksius\LimbahInfeksiusCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.limbah-infeksius',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\Alasan\AlasanEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.alasan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\Alasan\AlasanCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.alasan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\KegiatanAlasan\KegiatanAlasanEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.kegiatan-alasan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\KegiatanAlasan\KegiatanAlasanCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.kegiatan-alasan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\AuditIndividu\AuditIndividuEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.audit-individu',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\AuditIndividu\AuditIndividuCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.audit-individu',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\XampleIndividu\XampleIndividuEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.xample-individu',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\XampleIndividu\XampleIndividuCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.xample-individu',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\XampelDetail\XampelDetailEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.xampel-detail',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\XampelDetail\XampelDetailCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.xampel-detail',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\GejalaIdo\GejalaIdoEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.gejala-ido',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\GejalaIdo\GejalaIdoCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.gejala-ido',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\TindakLanjut\TindakLanjutEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.tindak-lanjut',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\TindakLanjut\TindakLanjutCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.tindak-lanjut',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\Flebitis\FlebitisEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.flebitis',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\Flebitis\FlebitisCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.flebitis',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\Vap\VapEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.vap',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\Vap\VapCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.vap',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \PPI\V1\Rest\ISK\ISKEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.isk',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \PPI\V1\Rest\ISK\ISKCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'ppi.rest.isk',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
        ],
    ],
];
