USE aplikasi;

ALTER TABLE `info_teks`
	ADD COLUMN `JENIS` TINYINT(4) NOT NULL DEFAULT '1' AFTER `ID`,
	ADD COLUMN `WARNA` CHAR(10) NOT NULL DEFAULT '' AFTER `TEKS`,
	ADD COLUMN `PUBLISH` TINYINT NOT NULL DEFAULT 1 AFTER `WARNA`,
	ADD COLUMN `STATUS` TINYINT NOT NULL DEFAULT 1 AFTER `PUBLISH`,
	ADD INDEX `JENIS` (`JENIS`),
	ADD INDEX `PUBLISH` (`PUBLISH`),
	ADD INDEX `STATUS` (`STATUS`);

ALTER TABLE `info_teks`
	ADD COLUMN `TANGGAL` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() AFTER `PUBLISH`,
	ADD COLUMN `OLEH` SMALLINT NOT NULL AFTER `TANGGAL`;