<?php
return [
    'router' => [
        'routes' => [
            'inventory.rest.barang' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/barang[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\Barang\\Controller',
                    ],
                ],
            ],
            'inventory.rest.kategori' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/kategori[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\Kategori\\Controller',
                    ],
                ],
            ],
            'inventory.rest.satuan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/satuan[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\Satuan\\Controller',
                    ],
                ],
            ],
            'inventory.rest.penyedia' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/penyedia[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\Penyedia\\Controller',
                    ],
                ],
            ],
            'inventory.rest.barang-ruangan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/barangruangan[/:ruangan]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\BarangRuangan\\Controller',
                    ],
                ],
            ],
            'inventory.rest.penerimaan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/penerimaan[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\Penerimaan\\Controller',
                    ],
                ],
            ],
            'inventory.rest.permintaan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/permintaan[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\Permintaan\\Controller',
                    ],
                ],
            ],
            'inventory.rest.permintaan-detil' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/permintaandetil[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\PermintaanDetil\\Controller',
                    ],
                ],
            ],
            'inventory.rest.pengiriman' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/pengiriman[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\Pengiriman\\Controller',
                    ],
                ],
            ],
            'inventory.rest.pengiriman-detil' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/pengirimandetil[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\PengirimanDetil\\Controller',
                    ],
                ],
            ],
            'inventory.rest.harga-barang' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/hargabarang[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\HargaBarang\\Controller',
                    ],
                ],
            ],
            'inventory.rest.stok-opname' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/stokopname[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\StokOpname\\Controller',
                    ],
                ],
            ],
            'inventory.rest.stok-opname-detil' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/stokopnamedetil[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\StokOpnameDetil\\Controller',
                    ],
                ],
            ],
            'inventory.rest.transaksi-stok-ruangan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/transaksistokruangan[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\TransaksiStokRuangan\\Controller',
                    ],
                ],
            ],
            'inventory.rest.penerimaan-barang' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/penerimaanbarang[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\PenerimaanBarang\\Controller',
                    ],
                ],
            ],
            'inventory.rest.penerimaan-barang-detil' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/penerimaanbarangdetil[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\Controller',
                    ],
                ],
            ],
            'inventory.rest.pengembalian-barang' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/pengembalianbarang[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\PengembalianBarang\\Controller',
                    ],
                ],
            ],
            'inventory.rest.pengembalian-barang-detil' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/pengembalianbarangdetil[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\PengembalianBarangDetil\\Controller',
                    ],
                ],
            ],
            'inventory.rest.pembatalan-penerimaan-barang' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/pembatalanpenerimaanbarang[/:pembatalan_penerimaan_barang_id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\Controller',
                    ],
                ],
            ],
            'inventory.rest.stok-barang-minimum' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/stokbarangminimum[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\StokBarangMinimum\\Controller',
                    ],
                ],
            ],
            'inventory.rest.paket-farmasi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/paketfarmasi[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\PaketFarmasi\\Controller',
                    ],
                ],
            ],
            'inventory.rest.no-seri-barang-ruangan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/noseribarangruangan[/:no_seri_barang_ruangan_id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\NoSeriBarangRuangan\\Controller',
                    ],
                ],
            ],
            'inventory.rest.penggolongan-barang' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/inventory/barang/penggolongan[/:id]',
                    'defaults' => [
                        'controller' => 'Inventory\\V1\\Rest\\PenggolonganBarang\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'api-tools-versioning' => [
        'uri' => [
            0 => 'inventory.rest.barang',
            1 => 'inventory.rest.kategori',
            2 => 'inventory.rest.satuan',
            3 => 'inventory.rest.penyedia',
            4 => 'inventory.rest.barang-ruangan',
            6 => 'inventory.rest.penerimaan',
            7 => 'inventory.rest.permintaan',
            8 => 'inventory.rest.permintaan-detil',
            9 => 'inventory.rest.pengiriman',
            10 => 'inventory.rest.pengiriman-detil',
            11 => 'inventory.rest.harga-barang',
            13 => 'inventory.rest.stok-opname',
            14 => 'inventory.rest.stok-opname',
            15 => 'inventory.rest.stok-opname-detil',
            16 => 'inventory.rest.transaksi-stok-ruangan',
            17 => 'inventory.rest.penerimaan-barang',
            18 => 'inventory.rest.penerimaan-barang-detil',
            19 => 'inventory.rest.pengembalian-barang',
            20 => 'inventory.rest.pengembalian-barang-detil',
            21 => 'inventory.rest.pembatalan-penerimaan-barang',
            31 => 'inventory.rest.stok-barang-minimum',
            32 => 'inventory.rest.paket-farmasi',
            33 => 'inventory.rest.no-seri-barang-ruangan',
            34 => 'inventory.rest.penggolongan-barang',
        ],
    ],
    'service_manager' => [
        'factories' => [
            \Inventory\V1\Rest\Barang\BarangResource::class => \Inventory\V1\Rest\Barang\BarangResourceFactory::class,
            \Inventory\V1\Rest\Kategori\KategoriResource::class => \Inventory\V1\Rest\Kategori\KategoriResourceFactory::class,
            \Inventory\V1\Rest\Satuan\SatuanResource::class => \Inventory\V1\Rest\Satuan\SatuanResourceFactory::class,
            \Inventory\V1\Rest\Penyedia\PenyediaResource::class => \Inventory\V1\Rest\Penyedia\PenyediaResourceFactory::class,
            \Inventory\V1\Rest\BarangRuangan\BarangRuanganResource::class => \Inventory\V1\Rest\BarangRuangan\BarangRuanganResourceFactory::class,
            \Inventory\V1\Rest\Penerimaan\PenerimaanResource::class => \Inventory\V1\Rest\Penerimaan\PenerimaanResourceFactory::class,
            \Inventory\V1\Rest\Permintaan\PermintaanResource::class => \Inventory\V1\Rest\Permintaan\PermintaanResourceFactory::class,
            \Inventory\V1\Rest\PermintaanDetil\PermintaanDetilResource::class => \Inventory\V1\Rest\PermintaanDetil\PermintaanDetilResourceFactory::class,
            \Inventory\V1\Rest\Pengiriman\PengirimanResource::class => \Inventory\V1\Rest\Pengiriman\PengirimanResourceFactory::class,
            \Inventory\V1\Rest\PengirimanDetil\PengirimanDetilResource::class => \Inventory\V1\Rest\PengirimanDetil\PengirimanDetilResourceFactory::class,
            \Inventory\V1\Rest\HargaBarang\HargaBarangResource::class => \Inventory\V1\Rest\HargaBarang\HargaBarangResourceFactory::class,
            \Inventory\V1\Rest\StokOpname\StokOpnameResource::class => \Inventory\V1\Rest\StokOpname\StokOpnameResourceFactory::class,
            \Inventory\V1\Rest\StokOpnameDetil\StokOpnameDetilResource::class => \Inventory\V1\Rest\StokOpnameDetil\StokOpnameDetilResourceFactory::class,
            \Inventory\V1\Rest\TransaksiStokRuangan\TransaksiStokRuanganResource::class => \Inventory\V1\Rest\TransaksiStokRuangan\TransaksiStokRuanganResourceFactory::class,
            \Inventory\V1\Rest\PenerimaanBarang\PenerimaanBarangResource::class => \Inventory\V1\Rest\PenerimaanBarang\PenerimaanBarangResourceFactory::class,
            \Inventory\V1\Rest\PenerimaanBarangDetil\PenerimaanBarangDetilResource::class => \Inventory\V1\Rest\PenerimaanBarangDetil\PenerimaanBarangDetilResourceFactory::class,
            \Inventory\V1\Rest\PengembalianBarang\PengembalianBarangResource::class => \Inventory\V1\Rest\PengembalianBarang\PengembalianBarangResourceFactory::class,
            \Inventory\V1\Rest\PengembalianBarangDetil\PengembalianBarangDetilResource::class => \Inventory\V1\Rest\PengembalianBarangDetil\PengembalianBarangDetilResourceFactory::class,
            \Inventory\V1\Rest\PembatalanPenerimaanBarang\PembatalanPenerimaanBarangResource::class => \Inventory\V1\Rest\PembatalanPenerimaanBarang\PembatalanPenerimaanBarangResourceFactory::class,
            \Inventory\V1\Rest\StokBarangMinimum\StokBarangMinimumResource::class => \Inventory\V1\Rest\StokBarangMinimum\StokBarangMinimumResourceFactory::class,
            \Inventory\V1\Rest\PaketFarmasi\PaketFarmasiResource::class => \Inventory\V1\Rest\PaketFarmasi\PaketFarmasiResourceFactory::class,
            \Inventory\V1\Rest\NoSeriBarangRuangan\NoSeriBarangRuanganResource::class => \Inventory\V1\Rest\NoSeriBarangRuangan\NoSeriBarangRuanganResourceFactory::class,
            \Inventory\V1\Rest\PenggolonganBarang\PenggolonganBarangResource::class => \Inventory\V1\Rest\PenggolonganBarang\PenggolonganBarangResourceFactory::class,
        ],
    ],
    'api-tools-rest' => [
        'Inventory\\V1\\Rest\\Barang\\Controller' => [
            'listener' => \Inventory\V1\Rest\Barang\BarangResource::class,
            'route_name' => 'inventory.rest.barang',
            'route_identifier_name' => 'id',
            'collection_name' => 'barang',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ID',
                1 => 'NAMA',
                2 => 'KATEGORI',
                3 => 'QUERY',
                4 => 'start',
                5 => 'limit',
                6 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\Barang\BarangEntity::class,
            'collection_class' => \Inventory\V1\Rest\Barang\BarangCollection::class,
            'service_name' => 'Barang',
        ],
        'Inventory\\V1\\Rest\\Kategori\\Controller' => [
            'listener' => \Inventory\V1\Rest\Kategori\KategoriResource::class,
            'route_name' => 'inventory.rest.kategori',
            'route_identifier_name' => 'id',
            'collection_name' => 'kategori',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ID',
                1 => 'NAMA',
                2 => 'JENIS',
                3 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\Kategori\KategoriEntity::class,
            'collection_class' => \Inventory\V1\Rest\Kategori\KategoriCollection::class,
            'service_name' => 'Kategori',
        ],
        'Inventory\\V1\\Rest\\Satuan\\Controller' => [
            'listener' => \Inventory\V1\Rest\Satuan\SatuanResource::class,
            'route_name' => 'inventory.rest.satuan',
            'route_identifier_name' => 'id',
            'collection_name' => 'satuan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ID',
                1 => 'NAMA',
                2 => 'DESKRIPSI',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\Satuan\SatuanEntity::class,
            'collection_class' => \Inventory\V1\Rest\Satuan\SatuanCollection::class,
            'service_name' => 'Satuan',
        ],
        'Inventory\\V1\\Rest\\Penyedia\\Controller' => [
            'listener' => \Inventory\V1\Rest\Penyedia\PenyediaResource::class,
            'route_name' => 'inventory.rest.penyedia',
            'route_identifier_name' => 'id',
            'collection_name' => 'penyedia',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NAMA',
                1 => 'ALAMAT',
                2 => 'TELEPON',
                3 => 'QUERY',
                4 => 'start',
                5 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\Penyedia\PenyediaEntity::class,
            'collection_class' => \Inventory\V1\Rest\Penyedia\PenyediaCollection::class,
            'service_name' => 'Penyedia',
        ],
        'Inventory\\V1\\Rest\\BarangRuangan\\Controller' => [
            'listener' => \Inventory\V1\Rest\BarangRuangan\BarangRuanganResource::class,
            'route_name' => 'inventory.rest.barang-ruangan',
            'route_identifier_name' => 'ruangan',
            'collection_name' => 'barang_ruangan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'RUANGAN',
                1 => 'BARANG',
                2 => 'STATUS',
                3 => 'start',
                4 => 'limit',
                5 => 'QUERY',
                6 => 'KATEGORI',
                7 => 'KATEGORI_BARANG',
                8 => 'CEKSTOK',
                9 => 'JENIS_GENERIK',
                10 => 'KATEGORI_BARANG_INFEKSI',
                11 => 'KATEGORI_BARANG_NON_INFEKSI',
                12 => 'RUANGAN_DISTRIBUSI_BARANG',
                13 => 'BARANG_RS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\BarangRuangan\BarangRuanganEntity::class,
            'collection_class' => \Inventory\V1\Rest\BarangRuangan\BarangRuanganCollection::class,
            'service_name' => 'barangRuangan',
        ],
        'Inventory\\V1\\Rest\\Penerimaan\\Controller' => [
            'listener' => \Inventory\V1\Rest\Penerimaan\PenerimaanResource::class,
            'route_name' => 'inventory.rest.penerimaan',
            'route_identifier_name' => 'id',
            'collection_name' => 'penerimaan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOMOR',
                1 => 'JENIS',
                2 => 'REF',
                3 => 'STATUS',
                4 => 'start',
                5 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\Penerimaan\PenerimaanEntity::class,
            'collection_class' => \Inventory\V1\Rest\Penerimaan\PenerimaanCollection::class,
            'service_name' => 'Penerimaan',
        ],
        'Inventory\\V1\\Rest\\Permintaan\\Controller' => [
            'listener' => \Inventory\V1\Rest\Permintaan\PermintaanResource::class,
            'route_name' => 'inventory.rest.permintaan',
            'route_identifier_name' => 'id',
            'collection_name' => 'permintaan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOMOR',
                1 => 'ASAL',
                2 => 'TUJUAN',
                3 => 'STATUS',
                4 => 'start',
                5 => 'limit',
                6 => 'TERIMA',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\Permintaan\PermintaanEntity::class,
            'collection_class' => \Inventory\V1\Rest\Permintaan\PermintaanCollection::class,
            'service_name' => 'Permintaan',
        ],
        'Inventory\\V1\\Rest\\PermintaanDetil\\Controller' => [
            'listener' => \Inventory\V1\Rest\PermintaanDetil\PermintaanDetilResource::class,
            'route_name' => 'inventory.rest.permintaan-detil',
            'route_identifier_name' => 'id',
            'collection_name' => 'permintaan_detil',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'PERMINTAAN',
                1 => 'BARANG',
                2 => 'JUMLAH',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\PermintaanDetil\PermintaanDetilEntity::class,
            'collection_class' => \Inventory\V1\Rest\PermintaanDetil\PermintaanDetilCollection::class,
            'service_name' => 'PermintaanDetil',
        ],
        'Inventory\\V1\\Rest\\Pengiriman\\Controller' => [
            'listener' => \Inventory\V1\Rest\Pengiriman\PengirimanResource::class,
            'route_name' => 'inventory.rest.pengiriman',
            'route_identifier_name' => 'id',
            'collection_name' => 'pengiriman',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOMOR',
                1 => 'ASAL',
                2 => 'TUJUAN',
                3 => 'STATUS',
                4 => 'start',
                5 => 'limit',
                6 => 'PERMINTAAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\Pengiriman\PengirimanEntity::class,
            'collection_class' => \Inventory\V1\Rest\Pengiriman\PengirimanCollection::class,
            'service_name' => 'Pengiriman',
        ],
        'Inventory\\V1\\Rest\\PengirimanDetil\\Controller' => [
            'listener' => \Inventory\V1\Rest\PengirimanDetil\PengirimanDetilResource::class,
            'route_name' => 'inventory.rest.pengiriman-detil',
            'route_identifier_name' => 'id',
            'collection_name' => 'pengiriman_detil',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'PENGIRIMAN',
                1 => 'PERMINTAAN_BARANG_DETIL',
                2 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\PengirimanDetil\PengirimanDetilEntity::class,
            'collection_class' => \Inventory\V1\Rest\PengirimanDetil\PengirimanDetilCollection::class,
            'service_name' => 'PengirimanDetil',
        ],
        'Inventory\\V1\\Rest\\HargaBarang\\Controller' => [
            'listener' => \Inventory\V1\Rest\HargaBarang\HargaBarangResource::class,
            'route_name' => 'inventory.rest.harga-barang',
            'route_identifier_name' => 'id',
            'collection_name' => 'harga_barang',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'BARANG',
                1 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\HargaBarang\HargaBarangEntity::class,
            'collection_class' => \Inventory\V1\Rest\HargaBarang\HargaBarangCollection::class,
            'service_name' => 'HargaBarang',
        ],
        'Inventory\\V1\\Rest\\StokOpname\\Controller' => [
            'listener' => \Inventory\V1\Rest\StokOpname\StokOpnameResource::class,
            'route_name' => 'inventory.rest.stok-opname',
            'route_identifier_name' => 'id',
            'collection_name' => 'stok_opname',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'RUANGAN',
                1 => 'TANGGAL',
                2 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\StokOpname\StokOpnameEntity::class,
            'collection_class' => \Inventory\V1\Rest\StokOpname\StokOpnameCollection::class,
            'service_name' => 'StokOpname',
        ],
        'Inventory\\V1\\Rest\\StokOpnameDetil\\Controller' => [
            'listener' => \Inventory\V1\Rest\StokOpnameDetil\StokOpnameDetilResource::class,
            'route_name' => 'inventory.rest.stok-opname-detil',
            'route_identifier_name' => 'id',
            'collection_name' => 'stok_opname_detil',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STOK_OPNAME',
                1 => 'BARANG_RUANGAN',
                2 => 'TANGGAL',
                3 => 'QUERY',
                4 => 'KATEGORI',
                5 => 'start',
                6 => 'limit',
                7 => 'MANUAL',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\StokOpnameDetil\StokOpnameDetilEntity::class,
            'collection_class' => \Inventory\V1\Rest\StokOpnameDetil\StokOpnameDetilCollection::class,
            'service_name' => 'StokOpnameDetil',
        ],
        'Inventory\\V1\\Rest\\TransaksiStokRuangan\\Controller' => [
            'listener' => \Inventory\V1\Rest\TransaksiStokRuangan\TransaksiStokRuanganResource::class,
            'route_name' => 'inventory.rest.transaksi-stok-ruangan',
            'route_identifier_name' => 'id',
            'collection_name' => 'transaksi_stok_ruangan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'BARANG_RUANGAN',
                1 => 'JENIS',
                2 => 'FLAG',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\TransaksiStokRuangan\TransaksiStokRuanganEntity::class,
            'collection_class' => \Inventory\V1\Rest\TransaksiStokRuangan\TransaksiStokRuanganCollection::class,
            'service_name' => 'TransaksiStokRuangan',
        ],
        'Inventory\\V1\\Rest\\PenerimaanBarang\\Controller' => [
            'listener' => \Inventory\V1\Rest\PenerimaanBarang\PenerimaanBarangResource::class,
            'route_name' => 'inventory.rest.penerimaan-barang',
            'route_identifier_name' => 'id',
            'collection_name' => 'penerimaan_barang',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ID',
                1 => 'FAKTUR',
                2 => 'REKANAN',
                3 => 'STATUS',
                4 => 'start',
                5 => 'limit',
                6 => 'JENIS',
                7 => 'REF_PO',
                8 => 'sort',
            ],
            'page_size' => '25',
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\PenerimaanBarang\PenerimaanBarangEntity::class,
            'collection_class' => \Inventory\V1\Rest\PenerimaanBarang\PenerimaanBarangCollection::class,
            'service_name' => 'PenerimaanBarang',
        ],
        'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\Controller' => [
            'listener' => \Inventory\V1\Rest\PenerimaanBarangDetil\PenerimaanBarangDetilResource::class,
            'route_name' => 'inventory.rest.penerimaan-barang-detil',
            'route_identifier_name' => 'id',
            'collection_name' => 'penerimaan_barang_detil',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'PENERIMAAN',
                1 => 'BARANG',
                2 => 'NO_BATCH',
                3 => 'STATUS',
                4 => 'REF_PO_DETIL',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\PenerimaanBarangDetil\PenerimaanBarangDetilEntity::class,
            'collection_class' => \Inventory\V1\Rest\PenerimaanBarangDetil\PenerimaanBarangDetilCollection::class,
            'service_name' => 'PenerimaanBarangDetil',
        ],
        'Inventory\\V1\\Rest\\PengembalianBarang\\Controller' => [
            'listener' => \Inventory\V1\Rest\PengembalianBarang\PengembalianBarangResource::class,
            'route_name' => 'inventory.rest.pengembalian-barang',
            'route_identifier_name' => 'id',
            'collection_name' => 'pengembalian_barang',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'REKANAN',
                1 => 'TANGGAL',
                2 => 'STATUS',
                3 => 'RUANGAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\PengembalianBarang\PengembalianBarangEntity::class,
            'collection_class' => \Inventory\V1\Rest\PengembalianBarang\PengembalianBarangCollection::class,
            'service_name' => 'PengembalianBarang',
        ],
        'Inventory\\V1\\Rest\\PengembalianBarangDetil\\Controller' => [
            'listener' => \Inventory\V1\Rest\PengembalianBarangDetil\PengembalianBarangDetilResource::class,
            'route_name' => 'inventory.rest.pengembalian-barang-detil',
            'route_identifier_name' => 'id',
            'collection_name' => 'pengembalian_barang_detil',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'PENGEMBALIAN',
                1 => 'BARANG',
                2 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\PengembalianBarangDetil\PengembalianBarangDetilEntity::class,
            'collection_class' => \Inventory\V1\Rest\PengembalianBarangDetil\PengembalianBarangDetilCollection::class,
            'service_name' => 'PengembalianBarangDetil',
        ],
        'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\Controller' => [
            'listener' => \Inventory\V1\Rest\PembatalanPenerimaanBarang\PembatalanPenerimaanBarangResource::class,
            'route_name' => 'inventory.rest.pembatalan-penerimaan-barang',
            'route_identifier_name' => 'id',
            'collection_name' => 'pembatalan_penerimaan_barang',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'PENERIMAAN_BARANG',
                1 => 'JENIS',
                2 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\PembatalanPenerimaanBarang\PembatalanPenerimaanBarangEntity::class,
            'collection_class' => \Inventory\V1\Rest\PembatalanPenerimaanBarang\PembatalanPenerimaanBarangCollection::class,
            'service_name' => 'PembatalanPenerimaanBarang',
        ],
        'Inventory\\V1\\Rest\\StokBarangMinimum\\Controller' => [
            'listener' => \Inventory\V1\Rest\StokBarangMinimum\StokBarangMinimumResource::class,
            'route_name' => 'inventory.rest.stok-barang-minimum',
            'route_identifier_name' => 'id',
            'collection_name' => 'stok_barang_minimum',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'QUERY',
                1 => 'start',
                2 => 'limit',
            ],
            'page_size' => '25',
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\StokBarangMinimum\StokBarangMinimumEntity::class,
            'collection_class' => \Inventory\V1\Rest\StokBarangMinimum\StokBarangMinimumCollection::class,
            'service_name' => 'StokBarangMinimum',
        ],
        'Inventory\\V1\\Rest\\PaketFarmasi\\Controller' => [
            'listener' => \Inventory\V1\Rest\PaketFarmasi\PaketFarmasiResource::class,
            'route_name' => 'inventory.rest.paket-farmasi',
            'route_identifier_name' => 'id',
            'collection_name' => 'paket_farmasi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'BARANG',
                1 => 'TINDAKAN',
                2 => 'QUERY',
                3 => 'STATUS',
                4 => 'start',
                5 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\PaketFarmasi\PaketFarmasiEntity::class,
            'collection_class' => \Inventory\V1\Rest\PaketFarmasi\PaketFarmasiCollection::class,
            'service_name' => 'PaketFarmasi',
        ],
        'Inventory\\V1\\Rest\\NoSeriBarangRuangan\\Controller' => [
            'listener' => \Inventory\V1\Rest\NoSeriBarangRuangan\NoSeriBarangRuanganResource::class,
            'route_name' => 'inventory.rest.no-seri-barang-ruangan',
            'route_identifier_name' => 'no_seri_barang_ruangan_id',
            'collection_name' => 'no_seri_barang_ruangan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'BARANG_RUANGAN',
                1 => 'STATUS',
                2 => 'NO_SERI',
                3 => 'KONDISI_BARANG_PENERIMAAN',
                4 => 'STATUS_PENERIMAAN',
                5 => 'KONDISI_BARANG_DISTRIBUSI',
                6 => 'STATUS_DISTRIBUSI',
                7 => 'KONDISI_BARANG',
                8 => 'STATUS_DISTRIBUSI_FINAL',
                9 => 'KONDISI_BARANG_DISTRIBUSI_FINAL',
                10 => 'STATUS_PENERIMAAN_FINAL',
                11 => 'KONDISI_BARANG_PENERIMAAN_FINAL',
                12 => 'DISTRIBUSI_DETIL_LINEN',
                13 => 'PENERIMAAN_DETIL_LINEN',
                14 => 'LAYAK_PAKAI',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\NoSeriBarangRuangan\NoSeriBarangRuanganEntity::class,
            'collection_class' => \Inventory\V1\Rest\NoSeriBarangRuangan\NoSeriBarangRuanganCollection::class,
            'service_name' => 'NoSeriBarangRuangan',
        ],
        'Inventory\\V1\\Rest\\PenggolonganBarang\\Controller' => [
            'listener' => \Inventory\V1\Rest\PenggolonganBarang\PenggolonganBarangResource::class,
            'route_name' => 'inventory.rest.penggolongan-barang',
            'route_identifier_name' => 'id',
            'collection_name' => 'penggolongan_barang',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'BARANG',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventory\V1\Rest\PenggolonganBarang\PenggolonganBarangEntity::class,
            'collection_class' => \Inventory\V1\Rest\PenggolonganBarang\PenggolonganBarangCollection::class,
            'service_name' => 'PenggolonganBarang',
        ],
    ],
    'api-tools-content-negotiation' => [
        'controllers' => [
            'Inventory\\V1\\Rest\\Barang\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\Kategori\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\Satuan\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\Penyedia\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\BarangRuangan\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\Penerimaan\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\Permintaan\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PermintaanDetil\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\Pengiriman\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PengirimanDetil\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\HargaBarang\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\StokOpname\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\StokOpnameDetil\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\TransaksiStokRuangan\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PenerimaanBarang\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PengembalianBarang\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PengembalianBarangDetil\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\StokBarangMinimum\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PaketFarmasi\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\NoSeriBarangRuangan\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PenggolonganBarang\\Controller' => 'Json',
        ],
        'accept_whitelist' => [
            'Inventory\\V1\\Rest\\Barang\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\Kategori\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\Satuan\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\Penyedia\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\BarangRuangan\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\Penerimaan\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\Permintaan\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PermintaanDetil\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\Pengiriman\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PengirimanDetil\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\HargaBarang\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\StokOpname\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\StokOpnameDetil\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\TransaksiStokRuangan\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PenerimaanBarang\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PengembalianBarang\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PengembalianBarangDetil\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\StokBarangMinimum\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PaketFarmasi\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\NoSeriBarangRuangan\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PenggolonganBarang\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'Inventory\\V1\\Rest\\Barang\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\Kategori\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\Satuan\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\Penyedia\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\BarangRuangan\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\Penerimaan\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\Permintaan\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PermintaanDetil\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\Pengiriman\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PengirimanDetil\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\HargaBarang\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\StokOpname\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\StokOpnameDetil\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\TransaksiStokRuangan\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PenerimaanBarang\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PengembalianBarang\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PengembalianBarangDetil\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\StokBarangMinimum\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PaketFarmasi\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\NoSeriBarangRuangan\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
            'Inventory\\V1\\Rest\\PenggolonganBarang\\Controller' => [
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'api-tools-hal' => [
        'metadata_map' => [
            \Inventory\V1\Rest\Barang\BarangEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.barang',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\Barang\BarangCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.barang',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\Kategori\KategoriEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.kategori',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\Kategori\KategoriCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.kategori',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\Satuan\SatuanEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.satuan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\Satuan\SatuanCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.satuan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\Penyedia\PenyediaEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.penyedia',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\Penyedia\PenyediaCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.penyedia',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\BarangRuangan\BarangRuanganEntity::class => [
                'entity_identifier_name' => 'RUANGAN',
                'route_name' => 'inventory.rest.barang-ruangan',
                'route_identifier_name' => 'ruangan',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\BarangRuangan\BarangRuanganCollection::class => [
                'entity_identifier_name' => 'RUANGAN',
                'route_name' => 'inventory.rest.barang-ruangan',
                'route_identifier_name' => 'ruangan',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\Penerimaan\PenerimaanEntity::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'inventory.rest.penerimaan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\Penerimaan\PenerimaanCollection::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'inventory.rest.penerimaan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\Permintaan\PermintaanEntity::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'inventory.rest.permintaan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\Permintaan\PermintaanCollection::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'inventory.rest.permintaan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\PermintaanDetil\PermintaanDetilEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.permintaan-detil',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\PermintaanDetil\PermintaanDetilCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.permintaan-detil',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\Pengiriman\PengirimanEntity::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'inventory.rest.pengiriman',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\Pengiriman\PengirimanCollection::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'inventory.rest.pengiriman',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\PengirimanDetil\PengirimanDetilEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.pengiriman-detil',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\PengirimanDetil\PengirimanDetilCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.pengiriman-detil',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\HargaBarang\HargaBarangEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.harga-barang',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\HargaBarang\HargaBarangCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.harga-barang',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\StokOpname\StokOpnameEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.stok-opname',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\StokOpname\StokOpnameCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.stok-opname',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\StokOpnameDetil\StokOpnameDetilEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.stok-opname-detil',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\StokOpnameDetil\StokOpnameDetilCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.stok-opname-detil',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\TransaksiStokRuangan\TransaksiStokRuanganEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.transaksi-stok-ruangan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\TransaksiStokRuangan\TransaksiStokRuanganCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.transaksi-stok-ruangan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\PenerimaanBarang\PenerimaanBarangEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.penerimaan-barang',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\PenerimaanBarang\PenerimaanBarangCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.penerimaan-barang',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\PenerimaanBarangDetil\PenerimaanBarangDetilEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.penerimaan-barang-detil',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\PenerimaanBarangDetil\PenerimaanBarangDetilCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.penerimaan-barang-detil',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\PengembalianBarang\PengembalianBarangEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.pengembalian-barang',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\PengembalianBarang\PengembalianBarangCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.pengembalian-barang',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\PengembalianBarangDetil\PengembalianBarangDetilEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.pengembalian-barang-detil',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \Inventory\V1\Rest\PengembalianBarangDetil\PengembalianBarangDetilCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventory.rest.pengembalian-barang-detil',
                'route_identifier_name' => 'pengembalian_barang_detil_id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\PembatalanPenerimaanBarang\PembatalanPenerimaanBarangEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.pembatalan-penerimaan-barang',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Inventory\V1\Rest\PembatalanPenerimaanBarang\PembatalanPenerimaanBarangCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.pembatalan-penerimaan-barang',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\StokBarangMinimum\StokBarangMinimumEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.stok-barang-minimum',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Inventory\V1\Rest\StokBarangMinimum\StokBarangMinimumCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.stok-barang-minimum',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\PaketFarmasi\PaketFarmasiEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.paket-farmasi',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Inventory\V1\Rest\PaketFarmasi\PaketFarmasiCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.paket-farmasi',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\NoSeriBarangRuangan\NoSeriBarangRuanganEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventory.rest.no-seri-barang-ruangan',
                'route_identifier_name' => 'no_seri_barang_ruangan_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializable::class,
            ],
            \Inventory\V1\Rest\NoSeriBarangRuangan\NoSeriBarangRuanganCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventory.rest.no-seri-barang-ruangan',
                'route_identifier_name' => 'no_seri_barang_ruangan_id',
                'is_collection' => true,
            ],
            \Inventory\V1\Rest\PenggolonganBarang\PenggolonganBarangEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.penggolongan-barang',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Inventory\V1\Rest\PenggolonganBarang\PenggolonganBarangCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.penggolongan-barang',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
        ],
    ],
];
