USE inventory;

ALTER TABLE `penerimaan_barang`
	ADD COLUMN `TANGGAL_PENERIMAAN` DATETIME NULL COMMENT 'Tanggal Penerimaan Barang' AFTER `TANGGAL`,
	CHANGE COLUMN `TANGGAL_DIBUAT` `TANGGAL_DIBUAT` DATETIME NOT NULL COMMENT 'Tanggal di input' AFTER `MASA_BERLAKU`;