USE aplikasi;

ALTER TABLE `modules`
	CHANGE COLUMN `ID` `ID` CHAR(20) NOT NULL FIRST;

ALTER TABLE `group_pengguna_akses_module`
	CHANGE COLUMN `MODUL` `MODUL` CHAR(20) NOT NULL AFTER `GROUP_PENGGUNA`;