USE pendaftaran;

ALTER TABLE `kunjungan`
	ADD COLUMN `FINAL_HASIL` TINYINT NOT NULL DEFAULT 0 AFTER `STATUS`,
	ADD COLUMN `FINAL_HASIL_OLEH` SMALLINT NULL AFTER `FINAL_HASIL`,
	ADD COLUMN `FINAL_HASIL_TANGGAL` DATETIME NULL AFTER `FINAL_HASIL_OLEH`,
	ADD INDEX `FINAL_HASIL` (`FINAL_HASIL`);