<?php
return [
    'router' => [
        'routes' => [
            'pembayaran.rest.tagihan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/tagihan[/:id]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\Tagihan\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.transaksi-kasir' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/transaksikasir[/:nomor]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\TransaksiKasir\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.rincian-tagihan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/rinciantagihan[/:ref_id]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\RincianTagihan\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.penjamin-tagihan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/penjamintagihan[/:tagihan]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\PenjaminTagihan\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.edc' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/edc[/:tagihan]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\EDC\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.tagihan-pendaftaran' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/tagihanpendaftaran[/:tagihan]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\TagihanPendaftaran\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.diskon' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/diskon[/:tagihan]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\Diskon\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.diskon-dokter' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/diskondokter[/:tagihan]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\DiskonDokter\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.pembayaran-tagihan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/pembayarantagihan[/:tagihan]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\PembayaranTagihan\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.piutang-pasien' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/piutangpasien[/:tagihan]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\PiutangPasien\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.piutang-perusahaan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/piutangperusahaan[/:tagihan]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\PiutangPerusahaan\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.rincian-tagihan-paket' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/rinciantagihanpaket[/:tagihan]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\RincianTagihanPaket\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.deposit' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/deposit[/:tagihan]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\Deposit\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.pengembalian-deposit' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/pengembaliandeposit[/:tagihan]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\PengembalianDeposit\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.gabung-tagihan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/gabungtagihan[/:id]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\GabungTagihan\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.pembatalan-tagihan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/pembatalantagihan[/:id]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\PembatalanTagihan\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.kasir' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/kasir[/:id]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\Kasir\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.subsidi-tagihan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/subsiditagihan[/:id]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\SubsidiTagihan\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.pelunasan-piutang-pasien' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/pelunasanpiutang/pasien[/:id]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\PelunasanPiutangPasien\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.pelunasan-piutang-perusahaan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/pelunasanpiutang/perusahaan[/:id]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\PelunasanPiutangPerusahaan\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.transfer' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/transfer[/:id]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\Transfer\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.penyedia' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/penyedia[/:penyedia_id]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\Penyedia\\Controller',
                    ],
                ],
            ],
            'pembayaran.rest.layanan-penyedia' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/pembayaran/layanan-penyedia[/:layanan_penyedia_id]',
                    'defaults' => [
                        'controller' => 'Pembayaran\\V1\\Rest\\LayananPenyedia\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'api-tools-versioning' => [
        'uri' => [
            0 => 'pembayaran.rest.tagihan',
            1 => 'pembayaran.rest.transaksi-kasir',
            2 => 'pembayaran.rest.rincian-tagihan',
            3 => 'pembayaran.rest.penjamin-tagihan',
            4 => 'pembayaran.rest.edc',
            5 => 'pembayaran.rest.tagihan-pendaftaran',
            6 => 'pembayaran.rest.diskon',
            7 => 'pembayaran.rest.diskon-dokter',
            8 => 'pembayaran.rest.pembayaran-tagihan',
            9 => 'pembayaran.rest.piutang-pasien',
            10 => 'pembayaran.rest.piutang-perusahaan',
            11 => 'pembayaran.rest.rincian-tagihan-paket',
            12 => 'pembayaran.rest.deposit',
            13 => 'pembayaran.rest.pengembalian-deposit',
            14 => 'pembayaran.rest.gabung-tagihan',
            15 => 'pembayaran.rest.pembatalan-tagihan',
            16 => 'pembayaran.rest.kasir',
            17 => 'pembayaran.rest.subsidi-tagihan',
            18 => 'pembayaran.rest.pelunasan-piutang-pasien',
            19 => 'pembayaran.rest.pelunasan-piutang-perusahaan',
            20 => 'pembayaran.rest.transfer',
            21 => 'pembayaran.rest.penyedia',
            22 => 'pembayaran.rest.layanan-penyedia',
        ],
    ],
    'service_manager' => [
        'factories' => [
            \Pembayaran\V1\Rest\Tagihan\TagihanResource::class => \Pembayaran\V1\Rest\Tagihan\TagihanResourceFactory::class,
            \Pembayaran\V1\Rest\TransaksiKasir\TransaksiKasirResource::class => \Pembayaran\V1\Rest\TransaksiKasir\TransaksiKasirResourceFactory::class,
            \Pembayaran\V1\Rest\RincianTagihan\RincianTagihanResource::class => \Pembayaran\V1\Rest\RincianTagihan\RincianTagihanResourceFactory::class,
            \Pembayaran\V1\Rest\PenjaminTagihan\PenjaminTagihanResource::class => \Pembayaran\V1\Rest\PenjaminTagihan\PenjaminTagihanResourceFactory::class,
            \Pembayaran\V1\Rest\EDC\EDCResource::class => \Pembayaran\V1\Rest\EDC\EDCResourceFactory::class,
            \Pembayaran\V1\Rest\TagihanPendaftaran\TagihanPendaftaranResource::class => \Pembayaran\V1\Rest\TagihanPendaftaran\TagihanPendaftaranResourceFactory::class,
            \Pembayaran\V1\Rest\Diskon\DiskonResource::class => \Pembayaran\V1\Rest\Diskon\DiskonResourceFactory::class,
            \Pembayaran\V1\Rest\DiskonDokter\DiskonDokterResource::class => \Pembayaran\V1\Rest\DiskonDokter\DiskonDokterResourceFactory::class,
            \Pembayaran\V1\Rest\PembayaranTagihan\PembayaranTagihanResource::class => \Pembayaran\V1\Rest\PembayaranTagihan\PembayaranTagihanResourceFactory::class,
            \Pembayaran\V1\Rest\PiutangPasien\PiutangPasienResource::class => \Pembayaran\V1\Rest\PiutangPasien\PiutangPasienResourceFactory::class,
            \Pembayaran\V1\Rest\PiutangPerusahaan\PiutangPerusahaanResource::class => \Pembayaran\V1\Rest\PiutangPerusahaan\PiutangPerusahaanResourceFactory::class,
            \Pembayaran\V1\Rest\RincianTagihanPaket\RincianTagihanPaketResource::class => \Pembayaran\V1\Rest\RincianTagihanPaket\RincianTagihanPaketResourceFactory::class,
            \Pembayaran\V1\Rest\Deposit\DepositResource::class => \Pembayaran\V1\Rest\Deposit\DepositResourceFactory::class,
            \Pembayaran\V1\Rest\PengembalianDeposit\PengembalianDepositResource::class => \Pembayaran\V1\Rest\PengembalianDeposit\PengembalianDepositResourceFactory::class,
            \Pembayaran\V1\Rest\GabungTagihan\GabungTagihanResource::class => \Pembayaran\V1\Rest\GabungTagihan\GabungTagihanResourceFactory::class,
            \Pembayaran\V1\Rest\PembatalanTagihan\PembatalanTagihanResource::class => \Pembayaran\V1\Rest\PembatalanTagihan\PembatalanTagihanResourceFactory::class,
            \Pembayaran\V1\Rest\Kasir\KasirResource::class => \Pembayaran\V1\Rest\Kasir\KasirResourceFactory::class,
            \Pembayaran\V1\Rest\SubsidiTagihan\SubsidiTagihanResource::class => \Pembayaran\V1\Rest\SubsidiTagihan\SubsidiTagihanResourceFactory::class,
            \Pembayaran\V1\Rest\PelunasanPiutangPasien\PelunasanPiutangPasienResource::class => \Pembayaran\V1\Rest\PelunasanPiutangPasien\PelunasanPiutangPasienResourceFactory::class,
            \Pembayaran\V1\Rest\PelunasanPiutangPerusahaan\PelunasanPiutangPerusahaanResource::class => \Pembayaran\V1\Rest\PelunasanPiutangPerusahaan\PelunasanPiutangPerusahaanResourceFactory::class,
            \Pembayaran\V1\Rest\Transfer\TransferResource::class => \Pembayaran\V1\Rest\Transfer\TransferResourceFactory::class,
            \Pembayaran\V1\Rest\Penyedia\PenyediaResource::class => \Pembayaran\V1\Rest\Penyedia\PenyediaResourceFactory::class,
            \Pembayaran\V1\Rest\LayananPenyedia\LayananPenyediaResource::class => \Pembayaran\V1\Rest\LayananPenyedia\LayananPenyediaResourceFactory::class,
        ],
    ],
    'api-tools-rest' => [
        'Pembayaran\\V1\\Rest\\Tagihan\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\Tagihan\TagihanResource::class,
            'route_name' => 'pembayaran.rest.tagihan',
            'route_identifier_name' => 'id',
            'collection_name' => 'tagihan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TANGGAL',
                1 => 'REF',
                2 => 'JENIS',
                3 => 'ID',
                4 => 'STATUS',
                5 => 'start',
                6 => 'limit',
                7 => 'COLUMNS',
                8 => 'REFERENSI',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\Tagihan\TagihanEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\Tagihan\TagihanCollection::class,
            'service_name' => 'Tagihan',
        ],
        'Pembayaran\\V1\\Rest\\TransaksiKasir\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\TransaksiKasir\TransaksiKasirResource::class,
            'route_name' => 'pembayaran.rest.transaksi-kasir',
            'route_identifier_name' => 'nomor',
            'collection_name' => 'transaksi_kasir',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOMOR',
                1 => 'KASIR',
                2 => 'BUKA',
                3 => 'TUTUP',
                4 => 'start',
                5 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\TransaksiKasir\TransaksiKasirEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\TransaksiKasir\TransaksiKasirCollection::class,
            'service_name' => 'TransaksiKasir',
        ],
        'Pembayaran\\V1\\Rest\\RincianTagihan\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\RincianTagihan\RincianTagihanResource::class,
            'route_name' => 'pembayaran.rest.rincian-tagihan',
            'route_identifier_name' => 'ref_id',
            'collection_name' => 'rincian_tagihan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TAGIHAN',
                1 => 'REF_ID',
                2 => 'JENIS',
                3 => 'TARIF_ID',
                4 => 'STATUS',
                5 => 'RINCIAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\RincianTagihan\RincianTagihanEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\RincianTagihan\RincianTagihanCollection::class,
            'service_name' => 'RincianTagihan',
        ],
        'Pembayaran\\V1\\Rest\\PenjaminTagihan\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\PenjaminTagihan\PenjaminTagihanResource::class,
            'route_name' => 'pembayaran.rest.penjamin-tagihan',
            'route_identifier_name' => 'tagihan',
            'collection_name' => 'penjamin_tagihan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
            ],
            'collection_query_whitelist' => [
                0 => 'TAGIHAN',
                1 => 'PENJAMIN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\PenjaminTagihan\PenjaminTagihanEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\PenjaminTagihan\PenjaminTagihanCollection::class,
            'service_name' => 'PenjaminTagihan',
        ],
        'Pembayaran\\V1\\Rest\\EDC\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\EDC\EDCResource::class,
            'route_name' => 'pembayaran.rest.edc',
            'route_identifier_name' => 'tagihan',
            'collection_name' => 'edc',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TAGIHAN',
                1 => 'BANK',
                2 => 'JENIS_KARTU',
                3 => 'NOMOR',
                4 => 'PENYEDIA_ID',
                5 => 'JENIS_LAYANAN_ID',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\EDC\EDCEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\EDC\EDCCollection::class,
            'service_name' => 'EDC',
        ],
        'Pembayaran\\V1\\Rest\\TagihanPendaftaran\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\TagihanPendaftaran\TagihanPendaftaranResource::class,
            'route_name' => 'pembayaran.rest.tagihan-pendaftaran',
            'route_identifier_name' => 'tagihan',
            'collection_name' => 'tagihan_pendaftaran',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TAGIHAN',
                1 => 'PENDAFTARAN',
                2 => 'STATUS',
                3 => 'REFERENSI',
                4 => 'UTAMA',
                5 => 'COLUMNS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\TagihanPendaftaran\TagihanPendaftaranEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\TagihanPendaftaran\TagihanPendaftaranCollection::class,
            'service_name' => 'TagihanPendaftaran',
        ],
        'Pembayaran\\V1\\Rest\\Diskon\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\Diskon\DiskonResource::class,
            'route_name' => 'pembayaran.rest.diskon',
            'route_identifier_name' => 'tagihan',
            'collection_name' => 'diskon',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TAGIHAN',
                1 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\Diskon\DiskonEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\Diskon\DiskonCollection::class,
            'service_name' => 'Diskon',
        ],
        'Pembayaran\\V1\\Rest\\DiskonDokter\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\DiskonDokter\DiskonDokterResource::class,
            'route_name' => 'pembayaran.rest.diskon-dokter',
            'route_identifier_name' => 'tagihan',
            'collection_name' => 'diskon_dokter',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TAGIHAN',
                1 => 'DOKTER',
                2 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\DiskonDokter\DiskonDokterEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\DiskonDokter\DiskonDokterCollection::class,
            'service_name' => 'DiskonDokter',
        ],
        'Pembayaran\\V1\\Rest\\PembayaranTagihan\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\PembayaranTagihan\PembayaranTagihanResource::class,
            'route_name' => 'pembayaran.rest.pembayaran-tagihan',
            'route_identifier_name' => 'tagihan',
            'collection_name' => 'pembayaran_tagihan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TAGIHAN',
                1 => 'JENIS',
                2 => 'REF',
                3 => 'STATUS',
                4 => 'JENIS_LAYANAN_ID',
                5 => 'PENYEDIA_ID',
                6 => 'NOT',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\PembayaranTagihan\PembayaranTagihanEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\PembayaranTagihan\PembayaranTagihanCollection::class,
            'service_name' => 'PembayaranTagihan',
        ],
        'Pembayaran\\V1\\Rest\\PiutangPasien\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\PiutangPasien\PiutangPasienResource::class,
            'route_name' => 'pembayaran.rest.piutang-pasien',
            'route_identifier_name' => 'tagihan',
            'collection_name' => 'piutang_pasien',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TAGIHAN',
                1 => 'SHDK',
                2 => 'NO_KARTU_IDENTITAS',
                3 => 'JENIS_KARTU',
                4 => 'STATUS',
                5 => 'NORM',
                6 => 'GET_TOTAL',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\PiutangPasien\PiutangPasienEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\PiutangPasien\PiutangPasienCollection::class,
            'service_name' => 'PiutangPasien',
        ],
        'Pembayaran\\V1\\Rest\\PiutangPerusahaan\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\PiutangPerusahaan\PiutangPerusahaanResource::class,
            'route_name' => 'pembayaran.rest.piutang-perusahaan',
            'route_identifier_name' => 'tagihan',
            'collection_name' => 'piutang_perusahaan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TAGIHAN',
                1 => 'PENJAMIN',
                2 => 'STATUS',
                3 => 'NORM',
                4 => 'GET_TOTAL',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\PiutangPerusahaan\PiutangPerusahaanEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\PiutangPerusahaan\PiutangPerusahaanCollection::class,
            'service_name' => 'PiutangPerusahaan',
        ],
        'Pembayaran\\V1\\Rest\\RincianTagihanPaket\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\RincianTagihanPaket\RincianTagihanPaketResource::class,
            'route_name' => 'pembayaran.rest.rincian-tagihan-paket',
            'route_identifier_name' => 'tagihan',
            'collection_name' => 'rincian_tagihan_paket',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TAGIHAN',
                1 => 'PAKET_DETIL',
                2 => 'REF_ID',
                3 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\RincianTagihanPaket\RincianTagihanPaketEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\RincianTagihanPaket\RincianTagihanPaketCollection::class,
            'service_name' => 'RincianTagihanPaket',
        ],
        'Pembayaran\\V1\\Rest\\Deposit\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\Deposit\DepositResource::class,
            'route_name' => 'pembayaran.rest.deposit',
            'route_identifier_name' => 'tagihan',
            'collection_name' => 'deposit',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TAGIHAN',
                1 => 'TANGGAL',
                2 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\Deposit\DepositEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\Deposit\DepositCollection::class,
            'service_name' => 'Deposit',
        ],
        'Pembayaran\\V1\\Rest\\PengembalianDeposit\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\PengembalianDeposit\PengembalianDepositResource::class,
            'route_name' => 'pembayaran.rest.pengembalian-deposit',
            'route_identifier_name' => 'tagihan',
            'collection_name' => 'pengembalian_deposit',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TAGIHAN',
                1 => 'TANGGAL',
                2 => 'NAMA_PENERIMA',
                3 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\PengembalianDeposit\PengembalianDepositEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\PengembalianDeposit\PengembalianDepositCollection::class,
            'service_name' => 'PengembalianDeposit',
        ],
        'Pembayaran\\V1\\Rest\\GabungTagihan\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\GabungTagihan\GabungTagihanResource::class,
            'route_name' => 'pembayaran.rest.gabung-tagihan',
            'route_identifier_name' => 'id',
            'collection_name' => 'gabung_tagihan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'DARI',
                1 => 'TANGGAL',
                2 => 'STATUS',
                3 => 'KE',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\GabungTagihan\GabungTagihanEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\GabungTagihan\GabungTagihanCollection::class,
            'service_name' => 'GabungTagihan',
        ],
        'Pembayaran\\V1\\Rest\\PembatalanTagihan\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\PembatalanTagihan\PembatalanTagihanResource::class,
            'route_name' => 'pembayaran.rest.pembatalan-tagihan',
            'route_identifier_name' => 'id',
            'collection_name' => 'pembatalan_tagihan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\PembatalanTagihan\PembatalanTagihanEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\PembatalanTagihan\PembatalanTagihanCollection::class,
            'service_name' => 'PembatalanTagihan',
        ],
        'Pembayaran\\V1\\Rest\\Kasir\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\Kasir\KasirResource::class,
            'route_name' => 'pembayaran.rest.kasir',
            'route_identifier_name' => 'id',
            'collection_name' => 'kasir',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'QUERY',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\Kasir\KasirEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\Kasir\KasirCollection::class,
            'service_name' => 'Kasir',
        ],
        'Pembayaran\\V1\\Rest\\SubsidiTagihan\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\SubsidiTagihan\SubsidiTagihanResource::class,
            'route_name' => 'pembayaran.rest.subsidi-tagihan',
            'route_identifier_name' => 'id',
            'collection_name' => 'subsidi_tagihan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TAGIHAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\SubsidiTagihan\SubsidiTagihanEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\SubsidiTagihan\SubsidiTagihanCollection::class,
            'service_name' => 'SubsidiTagihan',
        ],
        'Pembayaran\\V1\\Rest\\PelunasanPiutangPasien\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\PelunasanPiutangPasien\PelunasanPiutangPasienResource::class,
            'route_name' => 'pembayaran.rest.pelunasan-piutang-pasien',
            'route_identifier_name' => 'id',
            'collection_name' => 'pelunasan_piutang_pasien',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ID',
                1 => 'TAGIHAN_PIUTANG',
                2 => 'STATUS',
                3 => 'JENIS_PEMBAYARAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\PelunasanPiutangPasien\PelunasanPiutangPasienEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\PelunasanPiutangPasien\PelunasanPiutangPasienCollection::class,
            'service_name' => 'PelunasanPiutangPasien',
        ],
        'Pembayaran\\V1\\Rest\\PelunasanPiutangPerusahaan\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\PelunasanPiutangPerusahaan\PelunasanPiutangPerusahaanResource::class,
            'route_name' => 'pembayaran.rest.pelunasan-piutang-perusahaan',
            'route_identifier_name' => 'id',
            'collection_name' => 'pelunasan_piutang_perusahaan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ID',
                1 => 'TAGIHAN_PIUTANG',
                2 => 'PENJAMIN',
                3 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\PelunasanPiutangPerusahaan\PelunasanPiutangPerusahaanEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\PelunasanPiutangPerusahaan\PelunasanPiutangPerusahaanCollection::class,
            'service_name' => 'PelunasanPiutangPerusahaan',
        ],
        'Pembayaran\\V1\\Rest\\Transfer\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\Transfer\TransferResource::class,
            'route_name' => 'pembayaran.rest.transfer',
            'route_identifier_name' => 'id',
            'collection_name' => 'transfer',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TAGIHAN',
                1 => 'BANK_ASAL',
                2 => 'REKENING',
                3 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\Transfer\TransferEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\Transfer\TransferCollection::class,
            'service_name' => 'Transfer',
        ],
        'Pembayaran\\V1\\Rest\\Penyedia\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\Penyedia\PenyediaResource::class,
            'route_name' => 'pembayaran.rest.penyedia',
            'route_identifier_name' => 'penyedia_id',
            'collection_name' => 'penyedia',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'JENIS_PENYEDIA_ID',
                1 => 'STATUS_ID',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\Penyedia\PenyediaEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\Penyedia\PenyediaCollection::class,
            'service_name' => 'Penyedia',
        ],
        'Pembayaran\\V1\\Rest\\LayananPenyedia\\Controller' => [
            'listener' => \Pembayaran\V1\Rest\LayananPenyedia\LayananPenyediaResource::class,
            'route_name' => 'pembayaran.rest.layanan-penyedia',
            'route_identifier_name' => 'layanan_penyedia_id',
            'collection_name' => 'layanan_penyedia',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'PENYEDIA_ID',
                1 => 'JENIS_LAYANAN_ID',
                2 => 'STATUS_ID',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Pembayaran\V1\Rest\LayananPenyedia\LayananPenyediaEntity::class,
            'collection_class' => \Pembayaran\V1\Rest\LayananPenyedia\LayananPenyediaCollection::class,
            'service_name' => 'LayananPenyedia',
        ],
    ],
    'api-tools-content-negotiation' => [
        'controllers' => [
            'Pembayaran\\V1\\Rest\\Tagihan\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\TransaksiKasir\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\RincianTagihan\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\PenjaminTagihan\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\EDC\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\TagihanPendaftaran\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\Diskon\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\DiskonDokter\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\PembayaranTagihan\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\PiutangPasien\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\PiutangPerusahaan\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\RincianTagihanPaket\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\Deposit\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\PengembalianDeposit\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\GabungTagihan\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\PembatalanTagihan\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\Kasir\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\SubsidiTagihan\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\PelunasanPiutangPasien\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\PelunasanPiutangPerusahaan\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\Transfer\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\Penyedia\\Controller' => 'Json',
            'Pembayaran\\V1\\Rest\\LayananPenyedia\\Controller' => 'Json',
        ],
        'accept_whitelist' => [
            'Pembayaran\\V1\\Rest\\Tagihan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\TransaksiKasir\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\RincianTagihan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PenjaminTagihan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\EDC\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\TagihanPendaftaran\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\Diskon\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\DiskonDokter\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PembayaranTagihan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PiutangPasien\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PiutangPerusahaan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\RincianTagihanPaket\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\Deposit\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PengembalianDeposit\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\GabungTagihan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PembatalanTagihan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\Kasir\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\SubsidiTagihan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PelunasanPiutangPasien\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PelunasanPiutangPerusahaan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\Transfer\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\Penyedia\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\LayananPenyedia\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'Pembayaran\\V1\\Rest\\Tagihan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\TransaksiKasir\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\RincianTagihan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PenjaminTagihan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\EDC\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\TagihanPendaftaran\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\Diskon\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\DiskonDokter\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PembayaranTagihan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PiutangPasien\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PiutangPerusahaan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\RincianTagihanPaket\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\Deposit\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PengembalianDeposit\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\GabungTagihan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PembatalanTagihan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\Kasir\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\SubsidiTagihan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PelunasanPiutangPasien\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\PelunasanPiutangPerusahaan\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\Transfer\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\Penyedia\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
            'Pembayaran\\V1\\Rest\\LayananPenyedia\\Controller' => [
                0 => 'application/vnd.pembayaran.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'api-tools-hal' => [
        'metadata_map' => [
            \Pembayaran\V1\Rest\Tagihan\TagihanEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.tagihan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\Tagihan\TagihanCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.tagihan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\TransaksiKasir\TransaksiKasirEntity::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'pembayaran.rest.transaksi-kasir',
                'route_identifier_name' => 'nomor',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\TransaksiKasir\TransaksiKasirCollection::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'pembayaran.rest.transaksi-kasir',
                'route_identifier_name' => 'nomor',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\RincianTagihan\RincianTagihanEntity::class => [
                'entity_identifier_name' => 'REF_ID',
                'route_name' => 'pembayaran.rest.rincian-tagihan',
                'route_identifier_name' => 'ref_id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\RincianTagihan\RincianTagihanCollection::class => [
                'entity_identifier_name' => 'REF_ID',
                'route_name' => 'pembayaran.rest.rincian-tagihan',
                'route_identifier_name' => 'ref_id',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\PenjaminTagihan\PenjaminTagihanEntity::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.penjamin-tagihan',
                'route_identifier_name' => 'tagihan',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\PenjaminTagihan\PenjaminTagihanCollection::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.penjamin-tagihan',
                'route_identifier_name' => 'tagihan',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\EDC\EDCEntity::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.edc',
                'route_identifier_name' => 'tagihan',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\EDC\EDCCollection::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.edc',
                'route_identifier_name' => 'tagihan',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\TagihanPendaftaran\TagihanPendaftaranEntity::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.tagihan-pendaftaran',
                'route_identifier_name' => 'tagihan',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\TagihanPendaftaran\TagihanPendaftaranCollection::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.tagihan-pendaftaran',
                'route_identifier_name' => 'tagihan',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\Diskon\DiskonEntity::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.diskon',
                'route_identifier_name' => 'tagihan',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\Diskon\DiskonCollection::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.diskon',
                'route_identifier_name' => 'tagihan',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\DiskonDokter\DiskonDokterEntity::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.diskon-dokter',
                'route_identifier_name' => 'tagihan',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\DiskonDokter\DiskonDokterCollection::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.diskon-dokter',
                'route_identifier_name' => 'tagihan',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\PembayaranTagihan\PembayaranTagihanEntity::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.pembayaran-tagihan',
                'route_identifier_name' => 'tagihan',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\PembayaranTagihan\PembayaranTagihanCollection::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.pembayaran-tagihan',
                'route_identifier_name' => 'tagihan',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\PiutangPasien\PiutangPasienEntity::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.piutang-pasien',
                'route_identifier_name' => 'tagihan',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\PiutangPasien\PiutangPasienCollection::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.piutang-pasien',
                'route_identifier_name' => 'tagihan',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\PiutangPerusahaan\PiutangPerusahaanEntity::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.piutang-perusahaan',
                'route_identifier_name' => 'tagihan',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\PiutangPerusahaan\PiutangPerusahaanCollection::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.piutang-perusahaan',
                'route_identifier_name' => 'tagihan',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\RincianTagihanPaket\RincianTagihanPaketEntity::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.rincian-tagihan-paket',
                'route_identifier_name' => 'tagihan',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\RincianTagihanPaket\RincianTagihanPaketCollection::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.rincian-tagihan-paket',
                'route_identifier_name' => 'tagihan',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\Deposit\DepositEntity::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.deposit',
                'route_identifier_name' => 'tagihan',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\Deposit\DepositCollection::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.deposit',
                'route_identifier_name' => 'tagihan',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\PengembalianDeposit\PengembalianDepositEntity::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.pengembalian-deposit',
                'route_identifier_name' => 'tagihan',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\PengembalianDeposit\PengembalianDepositCollection::class => [
                'entity_identifier_name' => 'TAGIHAN',
                'route_name' => 'pembayaran.rest.pengembalian-deposit',
                'route_identifier_name' => 'tagihan',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\GabungTagihan\GabungTagihanEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.gabung-tagihan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\GabungTagihan\GabungTagihanCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.gabung-tagihan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\PembatalanTagihan\PembatalanTagihanEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.pembatalan-tagihan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\PembatalanTagihan\PembatalanTagihanCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.pembatalan-tagihan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\Kasir\KasirEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.kasir',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\Kasir\KasirCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.kasir',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\SubsidiTagihan\SubsidiTagihanEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.subsidi-tagihan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Hydrator\\ArraySerializableHydratore',
            ],
            \Pembayaran\V1\Rest\SubsidiTagihan\SubsidiTagihanCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.subsidi-tagihan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\PelunasanPiutangPasien\PelunasanPiutangPasienEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.pelunasan-piutang-pasien',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Pembayaran\V1\Rest\PelunasanPiutangPasien\PelunasanPiutangPasienCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.pelunasan-piutang-pasien',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\PelunasanPiutangPerusahaan\PelunasanPiutangPerusahaanEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.pelunasan-piutang-perusahaan',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Pembayaran\V1\Rest\PelunasanPiutangPerusahaan\PelunasanPiutangPerusahaanCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.pelunasan-piutang-perusahaan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\Transfer\TransferEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.transfer',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Pembayaran\V1\Rest\Transfer\TransferCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'pembayaran.rest.transfer',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\Penyedia\PenyediaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pembayaran.rest.penyedia',
                'route_identifier_name' => 'penyedia_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Pembayaran\V1\Rest\Penyedia\PenyediaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pembayaran.rest.penyedia',
                'route_identifier_name' => 'penyedia_id',
                'is_collection' => true,
            ],
            \Pembayaran\V1\Rest\LayananPenyedia\LayananPenyediaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pembayaran.rest.layanan-penyedia',
                'route_identifier_name' => 'layanan_penyedia_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \Pembayaran\V1\Rest\LayananPenyedia\LayananPenyediaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'pembayaran.rest.layanan-penyedia',
                'route_identifier_name' => 'layanan_penyedia_id',
                'is_collection' => true,
            ],
        ],
    ],
];
