USE ris;

ALTER TABLE `hl7_message`
	CHANGE COLUMN `ID` `ID` INT NOT NULL AUTO_INCREMENT COLLATE 'latin1_swedish_ci' FIRST,
	ADD COLUMN `TINDAKAN_MEDIS` CHAR(11) NOT NULL AFTER `ID`,
	ADD COLUMN `JENIS` TINYINT NOT NULL DEFAULT '0' COMMENT '0=ORM,1=ORU' AFTER `TINDAKAN_MEDIS`,
	ADD UNIQUE INDEX `TINDAKAN_MEDIS_JENIS` (`TINDAKAN_MEDIS`, `JENIS`);

RENAME TABLE `hl7_message` TO `hl7_logs`;

ALTER TABLE `hl7_logs`
	CHANGE COLUMN `STATUS` `STATUS` TINYINT NOT NULL DEFAULT '1' COMMENT '0=Batal; 1=Belum Terkirim; 2=Terkirim' AFTER `RESPONSE`;

ALTER TABLE `hl7_logs`
	ADD COLUMN `KIRIM` TINYINT NOT NULL DEFAULT 0 COMMENT '0=Belum Terkirim; 1=Terkirim' AFTER `RESPONSE`,
	CHANGE COLUMN `STATUS` `STATUS` TINYINT NOT NULL DEFAULT '1' COMMENT '0=Batal; 1=Aktif' AFTER `KIRIM`;

ALTER TABLE `hl7_logs`
	ADD COLUMN `TGL_REQUEST` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `JENIS`,
	ADD COLUMN `TGL_RESPONSE` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `REQUEST`;	