USE aplikasi;

REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`, `INTERNAL_PACKAGE`, `CRUD`, `C`, `R`, `U`, `D`) VALUES ('1214', 'TRANSAKSI PENJUALAN', 2, '', 1, NULL, NULL, 0, 0, NULL, 1, 0, 0, 0, 0, 0);
REPLACE INTO `modules` (`ID`, `NAMA`, `LEVEL`, `DESKRIPSI`, `STATUS`, `CLASS`, `ICON_CLS`, `HAVE_CHILD`, `MENU_HOME`, `PACKAGE_NAME`, `INTERNAL_PACKAGE`, `CRUD`, `C`, `R`, `U`, `D`) VALUES ('121401', 'FINAL TAGIHAN PENJUALAN', 3, '', 1, NULL, NULL, 0, 0, NULL, 1, 0, 0, 0, 0, 0);
